#This software is preliminary or provisional and is subject to revision. It is being provided to meet 
#the need for timely best science. The software has not received final approval by the U.S. Geological 
#Survey (USGS). No warranty, expressed or implied, is made by the USGS or the U.S. Government as to the 
#functionality of the software and related material nor shall the fact of release constitute any such 
#warranty. The software is provided on the condition that neither the USGS nor the U.S. Government shall 
#be held liable for any damages resulting from the authorized or unauthorized use of the software.

##################################################
## Script purpose: Calculate monthly condenser duty at thermoelectric plants for the continental United 
##                 States for 2008-2020.
## Date: 01/26/2023
## Author: Lillian Gorman Sanisaca (lgormansanisaca@usgs.gov)
## RequiredLibraries : importThermoEIA, EIAplantAssociation, condenserDuty, dplyr
##################################################

#path to compile keys file
pathKeys<-"C:/Users/lgorman/OneDrive - DOI/WBEEP/compiledConsumpWD_dataRelease/compiledKeys_2008-2020.csv"
#path to compiled crosswalks file
pathCrosswalks<-"C:/Users/lgorman/OneDrive - DOI/WBEEP/compiledConsumpWD_dataRelease/compileCrosswalks_2008-2020_updated_01.27.23.csv"
#path for output of CD results
outputData_path<-"C:/Users/lgorman/OneDrive - DOI/WBEEP/compiledManualBogens_2008-2020test2/"
#path for output of plant association results
pathWrite<-"D:/plant_association/Output/"
#path to save EIA data pulled from web
pathSaveEIA<-"D:/EIA_data/"

#run these lines first time only to install packages
# install.packages("importThermoEIA_1.0.tar.gz",type="source",repos=NULL)
# install.packages("EIAplantAssociation_1.0.tar.gz",type="source",repos=NULL)
# install.packages("condenserDuty_1.0.tar.gz",type="source",repos=NULL)

#########DO NOT EDIT BELOW THIS LINE#########
#load required libraries
library(importThermoEIA)
library(EIAplantAssociation)
library(condenserDuty)
library(dplyr)

#loop through years
years<-seq(2008,2020,1)
for (y in years){
  #set year for analysis
  eia_year<-y
  print(eia_year)
  
  #pull EIA data from web
  eia_webpull(eia_year,pathSaveEIA)
  
  #read in compiled crosswalk
  crosswalk<-read.csv(pathCrosswalks)
  #filter for this year
  crosswalk<-crosswalk %>% filter(YEAR==y)
  #save to temp dir
  tempPathCross<-paste0(tempdir(),"UserControlCrosswalk",eia_year,".xlsx")
  openxlsx::write.xlsx(crosswalk,file=tempPathCross,row.names=F,overwrite = T)
  
  #set parameters for importThermoEIA::import_EIAData
  path_InputData_Metafile<-tempPathCross
  path_EIAInputData<-paste0(pathSaveEIA,"/",eia_year)
  outputCSV<-F
  path_outputCSV<-NA
  useStandardCrosswalk<-FALSE
  prepCondenserDuty<-TRUE
  
  
  #read in Master Plant List from EIAplantAssociation package
  utils::data("masterPlantList")
  plantList<-masterPlantList[masterPlantList$year==eia_year,]
  
  #run import module
  inputData.list<-import_EIAData(path_InputData_Metafile,path_EIAInputData,outputCSV,
                                 path_outputCSV,prepCondenserDuty = prepCondenserDuty,
                                 eia_year=eia_year,useStandardCrosswalk=useStandardCrosswalk)
  
  #add MPL
  inputData.list$plantList<-plantList
  list2env(inputData.list, .GlobalEnv)
  
  #get compiled keys generated by EIAplantAssociation, includes manual edits
  allKeys<-read.csv(pathKeys)
  allKeys<-allKeys %>% filter(YEAR==eia_year)
  
  #format for input into condenserDuty model
  #format boiler-generator associations by Boiler.ID
  sheet3_key<-allKeys %>% select(Plant.Code,
                                 Boiler.ID,
                                 bogen,
                                 contains("Reported.Prime.Mover"),
                                 YEAR,
                                 plant_bo,
                                 plant_bo_bf.923,
                                 sheet3_key)
  sheet3_key<-sheet3_key %>% filter(sheet3_key==1)
  sheet3_key<-sheet3_key[!duplicated(sheet3_key),]
  sheet3_key<-sheet3_key %>% filter(!is.na(bogen))
  
  #format boiler-generator associations by Generator.ID
  sheet4_key<-allKeys %>% select(Plant.Code,
                                 Generator.ID,
                                 bogen,
                                 plant_gen,
                                 plant_gen.923,
                                 contains("Reported.Prime.Mover"),
                                 YEAR,
                                 sheet4_key)
  sheet4_key<-sheet4_key %>% filter(sheet4_key==1)
  sheet4_key<-sheet4_key[!duplicated(sheet4_key),]
  sheet4_key<-sheet4_key %>% filter(!is.na(bogen))
  
  #format boiler-generator-cooling associations
  bogencoo.key<-allKeys %>% select(Plant.Code,
                                   Boiler.ID,
                                   bogen,
                                   bogencoo,
                                   bogencoo.key)
  names(bogencoo.key)[names(bogencoo.key)=="bogen"]<-"Bogen"
  names(bogencoo.key)[names(bogencoo.key)=="bogencoo"]<-"combogencoo"
  bogencoo.key$combogen<-paste0("combogen^",bogencoo.key$Bogen)
  bogencoo.key<-bogencoo.key %>% filter(bogencoo.key==1)
  bogencoo.key<-bogencoo.key[!duplicated(bogencoo.key),]
  
  #format cooling types by boiler-generator-cooling associations
  combogencoo_cooly_type<-allKeys %>% select(Plant.Code,
                                             bogencoo,
                                             LAKE..OF..OC..RC.,
                                             RIVER..OF.,
                                             POND..OC..RC.,
                                             TOWER..RF..RI..RN.,
                                             DC,
                                             OS,
                                             combogencoo_cooly_type)
  combogencoo_cooly_type<-combogencoo_cooly_type %>% filter(combogencoo_cooly_type==1)
  
  #subset nuclear plant cooling types by boiler-generator-cooling associations
  combogencoo_cooly_type_nukes<-allKeys %>% select(Plant.Code,
                                                   bogencoo,
                                                   LAKE..OF..OC..RC.,
                                                   RIVER..OF.,
                                                   POND..OC..RC.,
                                                   TOWER..RF..RI..RN.,
                                                   DC,
                                                   OS,
                                                   combogencoo_cooly_type_nukes)
  combogencoo_cooly_type_nukes<-combogencoo_cooly_type_nukes %>% filter(combogencoo_cooly_type_nukes==1)
  combogencoo_cooly_type_nukes<-combogencoo_cooly_type_nukes[!duplicated(combogencoo_cooly_type_nukes),]
  combogencoo_cooly_type<-combogencoo_cooly_type[!duplicated(combogencoo_cooly_type),]
  
  #remove rows with all missing cooling type
  combogencoo_cooly_type<-aggregate(combogencoo_cooly_type[-c(1,2)],
                                    by=list(Plant.Code=combogencoo_cooly_type$Plant.Code,
                                            bogencoo=combogencoo_cooly_type$bogencoo),
                                    FUN=function(x) sum(x,na.rm=T))
  combogencoo_cooly_type[-c(1,2)]<-sapply(combogencoo_cooly_type[-c(1,2)], function(x) ifelse(x==0,NA,x))
  combogencoo_cooly_type_nukes<-aggregate(combogencoo_cooly_type_nukes[-c(1,2)],
                                          by=list(Plant.Code=combogencoo_cooly_type_nukes$Plant.Code,
                                                  bogencoo=combogencoo_cooly_type_nukes$bogencoo),
                                          FUN=function(x) sum(x,na.rm=T))
  combogencoo_cooly_type_nukes[-c(1,2)]<-sapply(combogencoo_cooly_type_nukes[-c(1,2)], function(x) ifelse(x==0,NA,x))
  
  
  
  #compile keys into bogen.out.list object
  bogen.out.list<-named.list(sheet3_key,sheet4_key,bogencoo.key,
                             combogencoo_cooly_type_nukes,combogencoo_cooly_type)
  
  #run CD model
  runCondenserDuty(outputData_path, inputData.list, bogen.out.list)
  write.csv(final_CD_w_nukes_cooling,file=paste0(outputData_path,"CD_results",eia_year,".csv"),row.names = F)
  #test same results
  CD<-read.csv(paste0(outputData_path,"CD_results",eia_year,".csv"))
  Cdtest<-read.csv(paste0("C:/Users/lgorman/OneDrive - DOI/WBEEP/compiledmanualBogens_2008-2020/CD_results",eia_year,".csv"))
  # message(eia_year)
  # message(identical(CD,Cdtest))
  # setdiff(CD,Cdtest)
    if (y==2008){
    outID<-data.frame(year=y,identical=identical(CD,Cdtest))
  }else{
    outID<-rbind(outID,data.frame(year=y,identical=identical(CD,Cdtest)))
  }
  diffCD<-setdiff(CD,Cdtest)
  diffCdtest<-setdiff(Cdtest,CD)
  write.csv(diffCD,file=paste0(outputData_path,"diffCD",eia_year,".csv"),row.names = F)
  write.csv(diffCdtest,file=paste0(outputData_path,"diffCdtest",eia_year,".csv"),row.names = F)
  
  #format wide to long and compile
  CD<-final_CD_w_nukes_cooling
  CD<-reshape2::melt(CD,id.vars=c("Plant.Code","percentAllocation","cooling"))
  CD$month<-sapply(CD$variable,function(x) strsplit(as.character(x),"_")[[1]][2])
  months <- c("january","february","march","april",
              "may", "june", "july", "august",
              "september", "october", "november", "december")
  CD$month<-sapply(CD$month,function(x) which(months==x))
  names(CD)[names(CD)=="value"]<-"condenserDuty"
  CD<-CD %>% select(Plant.Code,cooling,percentAllocation,month,condenserDuty)
  CD$YEAR<-rep(y,nrow(CD))

  if (y==2008){
    compileCD<-CD
  }else{
    compileCD<-rbind(compileCD,CD)
  }
  
  
  postProcessVars$YEAR<-rep(y,nrow(postProcessVars))
  if (y==2008){
    postProcess_all<-postProcessVars
  }else{
    postProcess_all<-rbind(postProcess_all,postProcessVars)
  }


}
write.csv(postProcess_all,file=paste0(outputData_path,"postProcessVars_2008-2020.csv"),row.names = F)
write.csv(compileCD,file=paste0(outputData_path,"monthlyCondenserDuty_2008-2020.csv"),row.names = F)