#'@title bogen_associate
#'@description Creates a list including a data.frame of boiler-generator (bogen) associations
#'using the `inputData.list$bogen`, `inputData.list$gen_fuel_data`, `inputData.list$boilerFuelData`,
#'`inputData.list$generation.data`,`inputData.list$gen_860`,`inputData.list$retiredGenerators`,
#'`inputData.list$boilerDesignData` and the `associate()` function.
#'@param analysisYear numeric value indicating the year of EIA data present in the `inputData.list`.
#'@param inputData.list list object generated by the importThermoEIA::import_EIAData() function 
#'This data is pulled from the EIA website (https://www.eia.gov/electricity/) for the year 
#'of 2015 and has been run through the necessary formatting to be used by the EIAplantAssociation 
#'package.  inputData.list should be in the same format as the example `inputData.list2015` data
#'object.
#'@param plantList data.frame indicating which plants to include in the analysis.  Must contain 
#'the column "Plant.Code".  The `data("masterPlantList")` data object contains a list of recommended
#'plants for analysis for the years 2008-2020.
#'@param select_RPM vector of character strings indicating which Reported.Prime.Mover types should be
#'included in the boiler-generator association output.
#'@param printStatus TRUE/FALSE indicating whether function status messages should print.
#'@return list object with the following contents \cr \cr 
#'\tabular{ll}{
#'`bogen.key` \tab data.frame containing boiler-generator (bogen) associations, flags 
#'detailed in the `data(ColumnLegend_metafile)`.  To view the `data(ColumnLegend_metafile)` object use 
#'the `writeColumnLegend_metafile()` function. \cr
#'`NA.BOILER.ID` \tab data.frame of all Generators that could not be associated with a non-missing Boiler.ID.
#'Note this does not exclude the plant from the `bogen.key` but condenserDuty will not be calculated at
#'the boiler-generator level it will be calculated at the Plant.Code-Reported.Prime.Mover level.  See 
#'Section ... in the EIAplantAssociation vignette. \cr
#'`bogen` \tab EIA boiler-generator association table with IDs modified using the `formatIDcol()` 
#'function \cr
#'`checkPlants` \tab vector of Plant.Codes flagged with "flag_floatingGen" described in 
#'`data(ColumnLegend_metafile)` and Section ... of the EIAplantAssociation vignette. \cr
#'`Boiler.ID_NotAssoc` \tab data.frame of Boiler.IDs found in `inputData.list$boilerFuelData` that 
#'are not present in the EIA boiler-generator association table `inputData.list$bogen` and cannot be
#'associated by any means other than a string matched flags in the `bogen.key$bga.source` as 
#'"fillwithGenID". \cr
#'`compare_RPM` \tab data frame of plants that have inconsistent Reported.Prime.Movers in the EIA
#'tables present in `inputData.list`.  These plants will be flagged with "flag_RPM" described in the 
#'`data(ColumnLegend_metafile)` \cr
#'`missingCSCT` \tab data.frame of Natural Gas Combined Cycle plants with inconsitent data reporting
#'in the EIA Form-923 across "Page 3 Boiler Fuel Data", "Page 4 Generator Data", and "Page 1 
#'Generation and Fuel Data".  If data is present on "Page 1 Generation and Fuel Data" and not in
#'"Page 3 Boiler Fuel Data" and/or "Page 4 Generator Data", the boiler-generator association will take
#'the form Plant.Code^NGCC and  the `condenserDuty` package will calculate condenser duty using 
#'"Page 1 Generation and Fuel Data" \cr
#'`manualPlants` \tab data.frame of Plants flagged for manual boiler-generator association checks and
#'which manual check flags were triggered.  See `data(ColumnLegend_metafile)` for descriptions of 
#'manual flags. \cr
#'`decembrist` \tab vector of Plant.Codes including plants that only reported Fuel Consumption and
#'Net Generation in the month of December on the EIA Form-923 "Page 3 Boiler Fuel Data" and 
#'"Page 4 Generator Data".  These plants will have a boiler-generator association in the form of 
#'Plant.Code^NGCC (for natural gas combined cycle units) or Plant.Code^ST (for steam units) and the
#'`condenserDuty` package will calculated condenser duty using data from "Page 1 Generation and 
#'Fuel Data" \cr
#'
#'}
#'@examples
#'#set arguments
#'dest<-tempdir()
#'eia_year<-2015
#'path_InputData_Metafile<-paste0(dest,.Platform$file.sep,"UserControlCrosswalk2015.xlsx")
#'path_EIAInputData<-paste0(dest,.Platform$file.sep,eia_year)
#'outputCSV<-FALSE
#'path_outputCSV<-dest
#'
#'#use crosswalk2015 object
#'useStandardCrosswalk<-TRUE
#'prepCondenserDuty<-TRUE
#'
#'#pull data from web
#'importThermoEIA::eia_webpull(eia_year,dest)
#'
#'
#'#run import using crosswalk2015
#'inputData.list<-importThermoEIA::import_EIAData(path_InputData_Metafile,path_EIAInputData,outputCSV,
#'                               path_outputCSV,prepCondenserDuty = TRUE,eia_year=eia_year,
#'                               useStandardCrosswalk=useStandardCrosswalk)
#'
#'#set year for analysis
#'eia_year<-2015
#'
#'#select Reported.Prime.Movers to include
#'select_RPM<-c("CA", "CS", "CT", "ST",NA)
#'
#'#load MasterPlantList
#'utils::data("masterPlantList")
#'plantList<-masterPlantList[masterPlantList$year==eia_year,]
#'
#'#run boiler-generator associations
#'bogen.key<-bogen_associate(analysisYear = eia_year,inputData.list,
#'                                           plantList,select_RPM)
#'
#'@export


bogen_associate <- function(analysisYear,inputData.list,plantList,
                            select_RPM,printStatus=T){
  if (printStatus){message("Loading Data and formatting ID columns")}
  myEnv<-environment()
  #unpack input data
  list2env(inputData.list,envir = parent.frame())

  generator.data<-gen_860
  
  #convert plantList to vector
  plantList<-plantList$Plant.Code
  
  #nukes
  nukes<-inputData.list$gen_fuel_data %>% dplyr::filter((!is.na(Nuclear.Unit.Id) & Nuclear.Unit.Id!=".") & 
                                                   Plant.Code %in% plantList)
  nonNukes<-inputData.list$gen_fuel_data %>% dplyr::filter((is.na(Nuclear.Unit.Id) & 
                                                       Reported.Prime.Mover %in% select_RPM &
                                                       Plant.Code %in% plantList) |
                                                      (Nuclear.Unit.Id=="." & 
                                                         Reported.Prime.Mover %in% select_RPM &
                                                         Plant.Code %in% plantList))
  
  #complexNukes
  complexNukes<-nonNukes[nonNukes$Plant.Code %in% nukes$Plant.Code,]$Plant.Code
  
  #nukeOnly plants
  nukePlants<-nukes %>% dplyr::filter(!Plant.Code %in% complexNukes)
  
  #define months
  months<-c("January","February","March","April","May",
            "June","July","August","September","October","November","December")
  
  if (printStatus){message("Finding plants missing from `inputData.list` tables present in plantList")}
  #flag Plant not in input table
  missingPlants<-fileMissingPlants(plantList,inputData.list)

  
  #These first few lines are only cleaning up the datasets and preparing them for the association process
  #Bogen table, set generator.id and boiler.id variables to character strings
  bogen<-bogen %>% dplyr::filter(Plant.Code %in% plantList)
  bogen$Generator.ID <- as.character(bogen$Generator.ID)
  bogen$Boiler.ID <- as.character(bogen$Boiler.ID)
  #Drop utlity id variable from bogen table
  bogen <- dplyr::select(bogen,-any_of(c("Utility.ID")))
  
  
  #flag changed IDS
  bogen<-formatIDcol(bogen,idCol="Generator.ID",
                     flagColname = "flagGenerator.ID_assoc",
                     originalColname="orig_Generator.ID_assoc") 
  
  bogen<-formatIDcol(bogen,idCol="Boiler.ID",
                    flagColname = "flagBoiler.ID_assoc",
                    originalColname="orig_Boiler.ID_assoc")  

  
  #Generator data
  #flag changed IDS
  gen_860 <- generator.data
  gen_860<-gen_860 %>% dplyr::filter(Plant.Code %in% plantList)
  gen_860<- gen_860 %>% dplyr::filter(!Plant.Code %in% nukePlants$Plant.Code)

  gen_860<-formatIDcol(gen_860,idCol="Generator.ID",
                     flagColname = "flagGenerator.ID_860",
                     originalColname="orig_Generator.ID_860") 
  

  
  #solid fuel gas select only Solid.Fuel.Gasification.System.=="Y"
  if (analysisYear>2003){
  solidGasPlants<-gen_860 %>% dplyr::filter(Solid.Fuel.Gasification.System.=="Y")
  }
  
  #compare inconsistent Reported.Prime.Movers across EIA tables
  compare_RPM_860<-dplyr::select(gen_860,c("Plant.Code","Generator.ID","flagGenerator.ID_860",
                                "orig_Generator.ID_860","Prime.Mover"))
  names(compare_RPM_860)[names(compare_RPM_860)=="Prime.Mover"]<-"Reported.Prime.Mover_860"
  
  
  names(gen_860)[names(gen_860)=="Prime.Mover"]<-"Reported.Prime.Mover_860"
  

  
  #Boiler generation data, set generator.id variable to character strings
  #flag changed IDS
  generation.data <- generation.data
  generation.data<-generation.data %>% dplyr::filter(Plant.Code %in% plantList)
  generation.data<- generation.data %>% dplyr::filter(!Plant.Code %in% nukePlants$Plant.Code)

  generation.data<-formatIDcol(generation.data,idCol="Generator.ID",
                       flagColname = "flagGenerator.ID_923",
                       originalColname="orig_Generator.ID_923")

  
  #compare inconsistent Reported.Prime.Movers across EIA tables
  if (analysisYear>2005){
  compare_RPM_923<-dplyr::select(generation.data,c("Plant.Code","Generator.ID","flagGenerator.ID_923",
                                "orig_Generator.ID_923","Reported.Prime.Mover"))
  names(compare_RPM_923)[names(compare_RPM_923)=="Reported.Prime.Mover"]<-"Reported.Prime.Mover_923"
  compare_RPM <- full_join_track(compare_RPM_860,compare_RPM_923,by=c("Plant.Code","Generator.ID"),.merge=F,all=T)
  

  #save crosswalk flag ids
  generation.flagIDs<-generation.data %>% dplyr::select(Plant.Code, Generator.ID,
                                                 Reported.Prime.Mover)
  }else{
    generation.flagIDs<-generation.data %>% dplyr::select(Plant.Code, Generator.ID)
  }
  generation.flagIDs<-generation.flagIDs[!duplicated(generation.flagIDs),]
  
 #save for use in executeBogenAssoc()
generation.data.line124<-generation.data
  assign("generation.data.line124",generation.data,envir = parent.frame())
  
  if (printStatus){message("Summing Net.Generation by Plant.Code and Generator.ID")}
  #sum all lines by plant and Generator.ID
  for(m in months){
    netGenstr<-paste0("sumbyGen<-generation.data %>% dplyr::group_by(Plant.Code,Generator.ID,orig_Generator.ID_923,flagGenerator.ID_923) %>%
                        dplyr::summarize(Generator.ID.Total.Net.Generation.",m,"=sum(Net.Generation.",m,",na.rm=T))")
    eval(parse(text=netGenstr))
    if (m=="January"){
      generation.data.gb<-sumbyGen
    }else{
      
      generation.data.gb<-merge(generation.data.gb,sumbyGen,by=c("Plant.Code","Generator.ID","orig_Generator.ID_923","flagGenerator.ID_923"),all=T)
    }
    
  }
  generation.data.gb2 <- generation.data %>% dplyr::group_by(.,Plant.Code,Generator.ID) %>% dplyr::summarise(Net.Generation.mwh=sum(Net.Generation.Year.To.Date,na.rm=T))
  generation.data.gb<-merge(generation.data.gb,generation.data.gb2,by=c("Plant.Code","Generator.ID"))
  
  #save for use in executeBogenAssoc()
  assign("generation.data.gb",generation.data.gb,envir = parent.frame())
  
  #sum all lines by plant
  for(m in months){
    netGenstr<-paste0("sumbyPlant<-generation.data.gb %>% dplyr::group_by(Plant.Code) %>% 
                        dplyr::summarize(PlantLine.Total.Net.Generation.",m,"=sum(Generator.ID.Total.Net.Generation.",m,",na.rm=T))")
    eval(parse(text=netGenstr))
    if (m=="January"){
      sumNetGenLinesByPlant<-sumbyPlant  
    }else{
      sumNetGenLinesByPlant<-merge(sumNetGenLinesByPlant,sumbyPlant,by="Plant.Code",all=T)
    }
    
  }
  #save for use in executeBogenAssoc()

  gen_923<-generation.data.gb
  

   #Create a variable to track which boilers are missing from the 923 report
  gen_923$missing.from.923 <- FALSE
  
  #merge gen_923 with flags
  gen_923<-merge(gen_923,generation.flagIDs, by=c("Plant.Code","Generator.ID"))
  if (analysisYear>2005){
    names(gen_923)[names(gen_923)=="Reported.Prime.Mover"]<-"Reported.Prime.Mover_923"
  }
  
  if (printStatus){message("Joining gen_860 and generation.data")}
  #Merge generator data and generation data 
  merged <- full_join_track(gen_860,gen_923,by=c("Plant.Code","Generator.ID"),.merge=T,all=T)
  missing.from.860 <- merged[merged$.merge=='right_only',]
  
  
  #Compile list of all generators
  gens <- full_join_track(gen_923,gen_860,by=c("Plant.Code","Generator.ID"),.merge=F,all=T)
  
  #gen.status
  names(gens)[names(gens)=="Status"]<-"Generator.Status"


  
   #Select columns to keep after merge
  if("Technology" %in% names(gens)){
  gens <- dplyr::select(gens,c("Plant.Code","Generator.ID","Unit.Code","missing.from.923",
                        "orig_Generator.ID_923","flagGenerator.ID_923","orig_Generator.ID_860","flagGenerator.ID_860",
                        "Reported.Prime.Mover_860","Reported.Prime.Mover_923","Technology",
                        "Energy.Source.1","Generator.Status",dplyr::contains("Net.Generation")),)
  }else{
    if (analysisYear>2005){
     gens <- dplyr::select(gens,c("Plant.Code","Generator.ID","Unit.Code","missing.from.923",
                          "orig_Generator.ID_923","flagGenerator.ID_923","orig_Generator.ID_860","flagGenerator.ID_860",
                          "Reported.Prime.Mover_860","Reported.Prime.Mover_923",
                          "Energy.Source.1","Generator.Status",dplyr::contains("Net.Generation")),)  
    }else{
      if (analysisYear>2003){
      gens <- dplyr::select(gens,c("Plant.Code","Generator.ID","Unit.Code","missing.from.923",
                            "orig_Generator.ID_923","flagGenerator.ID_923","orig_Generator.ID_860","flagGenerator.ID_860",
                            "Reported.Prime.Mover_860",
                            "Energy.Source.1","Generator.Status",dplyr::contains("Net.Generation")),)
      }else{
        gens <- dplyr::select(gens,c("Plant.Code","Generator.ID","missing.from.923",
                              "orig_Generator.ID_923","flagGenerator.ID_923","orig_Generator.ID_860","flagGenerator.ID_860",
                              "Reported.Prime.Mover_860",
                              "Energy.Source.1","Generator.Status",dplyr::contains("Net.Generation")),)
      }
    }
    
  }
  gens$Generator.ID <- as.character(gens$Generator.ID)
  gens <- dplyr::ungroup(gens)
  

  if (printStatus){message("Joining data by Generator.ID to bogen table")}
  
  #Linked bogen associations
  bga.1 <- full_join_track(gens,bogen,by=c("Plant.Code","Generator.ID"),.merge=F,all=T)
  bga.1 <- dplyr::select(bga.1,-any_of(c("Utility.Name","Plant.Name","Steam.Plant.Type")))

  #assigned bogens using the EIA bogen table
  bga_assn <- bga.1[!is.na(bga.1$Boiler.ID),]
  if (nrow(bga_assn)!=0){
  bga_assn$bga.source <- 'eia860.org'
  }else{
    bga_assn$bga.source <- character(0)
  }
  
  #Unlinked bogen associations
  bga_unassn <- bga.1[is.na(bga.1$Boiler.ID),]
  bga_unassn <- dplyr::select(bga_unassn,-c(Boiler.ID))
  
  #String Matching unassigned boilers based on fuel data
  bf.923 <- boilerFuelData
  
  #Drop Leading zeros in Boiler.ID
  bf.923<-bf.923 %>% dplyr::filter(Plant.Code %in% plantList)
  bf.923<- bf.923 %>% dplyr::filter(!Plant.Code %in% nukePlants$Plant.Code & Reported.Fuel.Type.Code!="NUC")
  
  bf.923<-formatIDcol(bf.923,idCol="Boiler.ID",
                    flagColname = "flagBoiler.ID_bf.923",
                    originalColname="orig_Boiler.ID_bf.923")
  
  
  bf.923$missing.bf.923 <- FALSE
  
  if (printStatus){message("Running Reported.Prime.Mover comparison across inputData.list tables")}
  if (analysisYear>2005){

  compare_RPM_bf.923<-dplyr::select(bf.923,c("Plant.Code","Boiler.ID","flagBoiler.ID_bf.923",
                                            "orig_Boiler.ID_bf.923","Reported.Prime.Mover"))
  names(compare_RPM_bf.923)[names(compare_RPM_bf.923)=="Reported.Prime.Mover"]<-"Reported.Prime.Mover_bf.923"
  compare_RPM <- full_join_track(compare_RPM,dplyr::select(bga.1,c("Plant.Code","Generator.ID","Boiler.ID")),
                                                    by=c("Plant.Code","Generator.ID"),.merge=F,all=T)
  compare_RPM <- full_join_track(compare_RPM,compare_RPM_bf.923,by=c("Plant.Code","Boiler.ID"),.merge=F,all=T)
  compare_RPM<-compare_RPM %>% dplyr::filter(Reported.Prime.Mover_860 %in% stats::na.omit(select_RPM) |
                                        Reported.Prime.Mover_923 %in% stats::na.omit(select_RPM) |
                                        Reported.Prime.Mover_bf.923 %in% stats::na.omit(select_RPM))
  
  compare3cols<-function(x,y,z){
    if (x!=y & !is.na(x) & !is.na(y)){
      flag<-1
    }else if (x!=z & !is.na(x) & !is.na(z)){
      flag<-1
    }else if (z!=y & !is.na(z) & !is.na(y)){
      flag<-1
    }else if (is.na(x) & is.na(y) & is.na(z)){
      flag<-1
    }else{
      flag<-0
    }
    return(flag)
  }
  
  compare_RPM<-compare_RPM %>% dplyr::rowwise() %>% dplyr::mutate(flag_RPM = compare3cols(Reported.Prime.Mover_860,
                                                              Reported.Prime.Mover_923,
                                                              Reported.Prime.Mover_bf.923))
  compare_RPM<-compare_RPM %>% dplyr::filter(flag_RPM==1)
  compare_RPM<-dplyr::select(compare_RPM, c("Plant.Code","Generator.ID","Boiler.ID",
                                     "orig_Generator.ID_860","flagGenerator.ID_860",
                                     "orig_Generator.ID_923","flagGenerator.ID_923",
                                     "orig_Boiler.ID_bf.923","flagBoiler.ID_bf.923",
                                     "Reported.Prime.Mover_860",
                                     "Reported.Prime.Mover_923",
                                     "Reported.Prime.Mover_bf.923",
                                     "flag_RPM"))
  
}#analysisYear>2005
  
#find orphan Boilers
  orphanBoilerPlants<-bf.923 %>% dplyr::filter(is.na(Boiler.ID))
  orphanBoilerPlants<-unique(orphanBoilerPlants$Plant.Code)
  
  

  if (printStatus){message("Finding Boiler.ID missing from bogen table")}
  #check if boiler.IDs NOT in association table
  Boiler.ID_NotAssoc<-bf.923[0,]
  for (p in unique(bf.923$Plant.Code)){
    if (analysisYear>2005){
      dfSub<-bf.923[bf.923$Plant.Code==p & bf.923$Reported.Prime.Mover %in% stats::na.omit(select_RPM),]
    }else{
      dfSub<-bf.923[bf.923$Plant.Code==p,]
    }
    
    assSub<-bogen[bogen$Plant.Code==p,]
    testBoiler<-unique(dfSub$Boiler.ID)
    testBoiler<-testBoiler[!testBoiler %in% assSub$Boiler.ID]
    if (length(testBoiler)!=0){
      testBoiler<-dfSub %>% dplyr::filter(Boiler.ID %in% testBoiler)
      Boiler.ID_NotAssoc<-rbind(Boiler.ID_NotAssoc,testBoiler %>% dplyr::select(names(Boiler.ID_NotAssoc)))
    }
  }
  if (analysisYear>2005){
  names(Boiler.ID_NotAssoc)[names(Boiler.ID_NotAssoc)=="Reported.Prime.Mover"]<-"Reported.Prime.Mover_bf.923"
  names(bf.923)[names(bf.923)=="Reported.Prime.Mover"]<-"Reported.Prime.Mover_bf.923"
  }
  
  #New Fuel Heat Calculation added 9.29.21
  #calculate fuel heat on each line for each month by multiplying Quantity.Of.Fuel.Consumed*MMbtu.Per.Unit
  if (printStatus){message("Calculating Fuel Heat by Plant.Code and Boiler.ID")}
  for(m in months){
    fuelHeatstr<-paste0("bf.923<-bf.923 %>% dplyr::mutate(Fuel.Heat.",m,"=Quantity.Of.Fuel.Consumed.",m,"*MMbtu.Per.Unit.",m,")")
    eval(parse(text=fuelHeatstr))
  }
  bf.923.ungrouped<-bf.923 
  
  
  #sum all lines by plant
  for(m in months){
    fuelHeatstr<-paste0("sumbyPlant<-bf.923 %>% dplyr::group_by(Plant.Code) %>% 
                        dplyr::summarize(PlantLine.Total.Fuel.Heat.",m,"=sum(Fuel.Heat.",m,",na.rm=T))")
    eval(parse(text=fuelHeatstr))
    if (m=="January"){
    sumFuelHeatLinesByPlant<-sumbyPlant  
    }else{
      sumFuelHeatLinesByPlant<-merge(sumFuelHeatLinesByPlant,sumbyPlant,by="Plant.Code",all=T)
    }
    
  }
 
  
  #sum all lines by plant and Boiler.ID
  
  for(m in months){
    fuelHeatstr<-paste0("sumbyBoiler<-bf.923 %>% dplyr::group_by(Plant.Code,Boiler.ID,
                                                          orig_Boiler.ID_bf.923,flagBoiler.ID_bf.923,missing.bf.923) %>% 
                        dplyr::summarize(Boiler.ID.Total.Fuel.Heat.",m,"=sum(Fuel.Heat.",m,",na.rm=T))")
    eval(parse(text=fuelHeatstr))
    if (m=="January"){
      bfd.gb<-sumbyBoiler  
    }else{

      bfd.gb<-merge(bfd.gb,sumbyBoiler,by=c("Plant.Code","Boiler.ID",
                                            "orig_Boiler.ID_bf.923","flagBoiler.ID_bf.923","missing.bf.923"),all=T)
    }
    
  }
  assign("bfd.gb",bfd.gb,envir = parent.frame())
 
  #Get unique Boiler.IDs ???????????Question this step
  bfd.923 <- dplyr::ungroup(bfd.gb)
  
  

  #add flags
  if (analysisYear>2005){
     bf_flagIDs<-bf.923 %>% dplyr::select(Plant.Code, Boiler.ID, #orig_Boiler.ID_bf.923,flagBoiler.ID_bf.923,
                                Reported.Prime.Mover_bf.923,Reported.Fuel.Type.Code) 
  }else{
    bf_flagIDs<-bf.923 %>% dplyr::select(Plant.Code, Boiler.ID) 
  }

  bf_flagIDs<-bf_flagIDs[!duplicated(bf_flagIDs),]
  bfd.923<-merge(bfd.923,bf_flagIDs,by=c("Plant.Code","Boiler.ID"))
  
 
  if (printStatus){message("Joining Data by Generator.ID and boilerFuelData table")}
  #add bfd columns to bga_assn
  bga_assn <- merge(bfd.923,bga_assn,by=c("Plant.Code","Boiler.ID"),all.y=T)

  #Create list of boilers not in bogen associations(bga) table
  bga.2 <- full_join_track(bfd.923,bga.1,by=c("Plant.Code","Boiler.ID"),.merge=T,all=T)
  bfd.not.in.bga <- bga.2[bga.2$.merge=="left_only",]
  bfd.not.in.bga <- dplyr::select(bfd.not.in.bga,-c(.merge))
  bfd.not.in.bga$Boiler.ID.2 <- bfd.not.in.bga$Boiler.ID
  
  #subset columns according to analysisYear
  if (analysisYear>2005){
    bfd.not.in.bga.formerge<-bfd.not.in.bga %>% dplyr::select(c("Plant.Code","Boiler.ID","Boiler.ID.2","Reported.Prime.Mover_bf.923","Reported.Fuel.Type.Code",
                                                       "orig_Boiler.ID_bf.923","flagBoiler.ID_bf.923","missing.bf.923"),dplyr::contains("Fuel.Heat")) 
  }else{
    bfd.not.in.bga.formerge<-bfd.not.in.bga %>% dplyr::select(c("Plant.Code","Boiler.ID","Boiler.ID.2",
                                                         "orig_Boiler.ID_bf.923","flagBoiler.ID_bf.923","missing.bf.923"),dplyr::contains("Fuel.Heat")) 
  }
 
   if (printStatus){message("Making string_assn matches")}
  bga_unassn.2 <- merge(bga_unassn,bfd.not.in.bga.formerge,
                        by.x=c("Plant.Code","Generator.ID"),by.y=c("Plant.Code","Boiler.ID"),all.x=T)
  names(bga_unassn.2)[names(bga_unassn.2)=="Boiler.ID.2"] <- "Boiler.ID"
  bga_unassn.2 <- bga_unassn.2[order(bga_unassn.2$Plant.Code),]
  bga_unassn.2$bga.source[!is.na(bga_unassn.2$Boiler.ID)] <- "string_assn"
  

  #Collection of all Bogens assigned and unassigned with their sources and assignment method
  bfd.not.in.bga<-dplyr::anti_join(bfd.not.in.bga,bga_unassn.2,by=c("Plant.Code","Boiler.ID"))
  

  
  Boiler.ID_NotAssoc<-dplyr::left_join(Boiler.ID_NotAssoc,bfd.not.in.bga %>% dplyr::select(c("Plant.Code","Boiler.ID"),dplyr::contains("Fuel.Heat")),by=c("Plant.Code","Boiler.ID"))
  
  #add in "NA" Boiler IDs
  bga.2 <- dplyr::bind_rows(bga_assn,bga_unassn.2)#,bfd.not.in.bga %>% dplyr::filter(Plant.Code==2059))
    
  #repeat with orig_Generator.ID_860
  if (nrow(bfd.not.in.bga)!=0){
    if (analysisYear>2005){
      bfd.not.in.bga.formerge<-bfd.not.in.bga %>% dplyr::select(c("Plant.Code","Boiler.ID","Boiler.ID.2","Reported.Prime.Mover_bf.923","Reported.Fuel.Type.Code",
                                                         "orig_Boiler.ID_bf.923","flagBoiler.ID_bf.923","missing.bf.923"),dplyr::contains("Fuel.Heat"))
    }else{
      bfd.not.in.bga.formerge<-bfd.not.in.bga %>% dplyr::select(c("Plant.Code","Boiler.ID","Boiler.ID.2",
                                                           "orig_Boiler.ID_bf.923","flagBoiler.ID_bf.923","missing.bf.923"),dplyr::contains("Fuel.Heat"))
    }
    
    
    bga_unassn.3 <- merge(bga_unassn,bfd.not.in.bga.formerge,
                          by.x=c("Plant.Code","orig_Generator.ID_860"),by.y=c("Plant.Code","Boiler.ID"),all.x=T)
    names(bga_unassn.3)[names(bga_unassn.3)=="Boiler.ID.2"] <- "Boiler.ID"
    bga_unassn.3 <- bga_unassn.3[order(bga_unassn.3$Plant.Code),]
    bga_unassn.3$bga.source[!is.na(bga_unassn.3$Boiler.ID)] <- "string_assn"
    
    bfd.not.in.bga<-dplyr::anti_join(bfd.not.in.bga,bga_unassn.3,by=c("Plant.Code","Boiler.ID"))
    Boiler.ID_NotAssoc<-dplyr::left_join(Boiler.ID_NotAssoc,bfd.not.in.bga %>% dplyr::select(c("Plant.Code","Boiler.ID"),dplyr::contains("Fuel.Heat")),by=c("Plant.Code","Boiler.ID"))
    
    #add in "NA" Boiler IDs
    bga.2 <- dplyr::bind_rows(bga.2,bga_unassn.3)
    
  }
  
  bga.2 <- bga.2[order(bga.2$Plant.Code),]
  
   bga.2$missing.from.923[is.na(bga.2$missing.from.923)] <- T
  bga.2$Boiler.ID <- as.character(as.factor(bga.2$Boiler.ID))

  
  bga.2$Boiler.ID <- dplyr::na_if(bga.2$Boiler.ID,"character(0)")
  if (analysisYear>2003){
  bga.2$Unit.Code <- dplyr::na_if(bga.2$Unit.Code,"")  
  
  
  if (printStatus){message("Making unit_connection matches")}
  #Connecting Bogens with Unit.Codes
  bga.2$Unit.Code <- dplyr::na_if(bga.2$Unit.Code,"")
  bga.2.units <- bga.2[!is.na(bga.2$Unit.Code),]
  if (analysisYear>2005){
   bga.2.gen.units <- dplyr::select(bga.2.units,-c(Boiler.ID, dplyr::contains("Boiler"),Reported.Prime.Mover_bf.923,Reported.Fuel.Type.Code,missing.bf.923)) 
   bga.2.boil.units <- dplyr::select(bga.2.units,c(Plant.Code,Boiler.ID,Unit.Code, dplyr::contains("Boiler"),Reported.Prime.Mover_bf.923,Reported.Fuel.Type.Code,missing.bf.923))
  }else{
    bga.2.gen.units <- dplyr::select(bga.2.units,-c(Boiler.ID, dplyr::contains("Boiler"),missing.bf.923)) 
    bga.2.boil.units <- dplyr::select(bga.2.units,c(Plant.Code,Boiler.ID,Unit.Code, dplyr::contains("Boiler"),missing.bf.923))
  }
  

  bga.2.boil.units <- subset(bga.2.boil.units,!is.na(Boiler.ID))

    na.Boiler.ID <- bga.2.units %>% subset(is.na(Boiler.ID))
 
  #Merge the boilers with units
  bga.unit.compilation <- full_join_track(bga.2.gen.units,bga.2.boil.units,by=c("Plant.Code","Unit.Code"))
  
  bga.unit.compilation$bga.source[is.na(bga.unit.compilation$bga.source)] <- 'unit_connection'
  
  #List of boilers with no unit code
  bga2.non.units <- bga.2 %>% subset(is.na(Unit.Code))

  bga.3 <- rbind(bga2.non.units,bga.unit.compilation)
  }else{#analysisYear>2003
  bga.3<-bga.2
  na.Boiler.ID <- bga.2 %>% subset(is.na(Boiler.ID))
    }
  bga.3 <- bga.3[order(bga.3$Plant.Code),]

  if ("Technology" %in% names(bga.3)){
  bga.3.1 <- bga.3 %>% dplyr::select(c(Plant.Code,Generator.ID,Boiler.ID,Unit.Code,bga.source,Net.Generation.mwh,missing.from.923,
                                orig_Generator.ID_923,flagGenerator.ID_923,orig_Generator.ID_860,flagGenerator.ID_860,
                                flagGenerator.ID_assoc, orig_Generator.ID_assoc,flagBoiler.ID_assoc,orig_Boiler.ID_assoc,
                                orig_Boiler.ID_bf.923,flagBoiler.ID_bf.923,missing.bf.923,
                                Reported.Prime.Mover_bf.923,Reported.Prime.Mover_923,Reported.Prime.Mover_860,Reported.Fuel.Type.Code,
                                Technology,Energy.Source.1,Generator.Status),dplyr::contains("Fuel.Heat"),
                              dplyr::contains("Generator.ID.Total.Net.Generation"))
  }else{
    if (analysisYear>2005){
      bga.3.1 <- bga.3 %>% dplyr::select(c(Plant.Code,Generator.ID,Boiler.ID,Unit.Code,bga.source,Net.Generation.mwh,missing.from.923,
                                    orig_Generator.ID_923,flagGenerator.ID_923,orig_Generator.ID_860,flagGenerator.ID_860,
                                    flagGenerator.ID_assoc, orig_Generator.ID_assoc,flagBoiler.ID_assoc,orig_Boiler.ID_assoc,
                                    orig_Boiler.ID_bf.923,flagBoiler.ID_bf.923,missing.bf.923,
                                    Reported.Prime.Mover_bf.923,Reported.Prime.Mover_923,Reported.Prime.Mover_860,Reported.Fuel.Type.Code,
                                    Energy.Source.1,Generator.Status),dplyr::contains("Fuel.Heat"),
                                  dplyr::contains("Generator.ID.Total.Net.Generation"))
    }else{
      if (analysisYear>2003){
    bga.3.1 <- bga.3 %>% dplyr::select(c(Plant.Code,Generator.ID,Boiler.ID,Unit.Code,bga.source,Net.Generation.mwh,missing.from.923,
                                  orig_Generator.ID_923,flagGenerator.ID_923,orig_Generator.ID_860,flagGenerator.ID_860,
                                  flagGenerator.ID_assoc, orig_Generator.ID_assoc,flagBoiler.ID_assoc,orig_Boiler.ID_assoc,
                                  orig_Boiler.ID_bf.923,flagBoiler.ID_bf.923,missing.bf.923,
                                  Reported.Prime.Mover_860,
                                  Energy.Source.1,Generator.Status),dplyr::contains("Fuel.Heat"),
                                dplyr::contains("Generator.ID.Total.Net.Generation"))
      }else{
        bga.3.1 <- bga.3 %>% dplyr::select(c(Plant.Code,Generator.ID,Boiler.ID,bga.source,Net.Generation.mwh,missing.from.923,
                                      orig_Generator.ID_923,flagGenerator.ID_923,orig_Generator.ID_860,flagGenerator.ID_860,
                                      flagGenerator.ID_assoc, orig_Generator.ID_assoc,flagBoiler.ID_assoc,orig_Boiler.ID_assoc,
                                      orig_Boiler.ID_bf.923,flagBoiler.ID_bf.923,missing.bf.923,
                                      Reported.Prime.Mover_860,
                                      Energy.Source.1,Generator.Status),dplyr::contains("Fuel.Heat"),
                                    dplyr::contains("Generator.ID.Total.Net.Generation"))
      }
    }
  }
  
  #Cleanup
  ##The next few lines address missing bogen associations that are listed in the bad plants list as either 
  #orphan boilers or orphan generators.
  #This line subsets the remaining bogen associations excluding any remaining missing Boiler.IDs. These boilers
  #are stored in the variable na.Boiler.ID
  na.Boiler.ID<-na.Boiler.ID %>% dplyr::select(names(bga.3.1))
  notNA.bga.3.1<-bga.3.1 %>% subset(!is.na(Boiler.ID))
  na.Boiler.ID<-dplyr::anti_join(na.Boiler.ID,notNA.bga.3.1, by=c("Plant.Code","Generator.ID"))
  na.Boiler.ID <- rbind(na.Boiler.ID,bga.3.1 %>% subset(is.na(Boiler.ID)))
  na.Boiler.ID<-na.Boiler.ID[!duplicated(na.Boiler.ID),]
  
  #Identify Plants with generation but no associated boilers
  genNoBoiler <- bga.3.1 %>% subset(is.na(Boiler.ID)&Net.Generation.mwh>0) 
  
  genNoBoiler <- as.data.frame(unique(genNoBoiler$Plant.Code))
  names(genNoBoiler) <- "Plant.Code"
  
  bga.3.2 <- full_join_track(genNoBoiler[1],bga.3.1,.merge = T,by="Plant.Code")
  bga.3.2$Orphan.Generator[bga.3.2$.merge=="matched"] <- T
  bga.3.2$Orphan.Generator[is.na(bga.3.2$Orphan.Generator)] <- F
  
  #Identify generators that are in the 923 report but not mapped
  bga.3.2$unmapped_but_in_923 <- rep(NA,nrow(bga.3.2))
  bga.3.2$unmapped_but_in_923[c(is.na(bga.3.2$Boiler.ID) & bga.3.2$missing.from.923==F & bga.3.2$Net.Generation.mwh==0)] <- T
  bga.3.2$unmapped_but_in_923[is.na(bga.3.2$unmapped_but_in_923)] <- F

  #Identify unmapped generators
  bga.3.2$unmapped <- rep(NA,nrow(bga.3.2))
  bga.3.2$unmapped[is.na(bga.3.2$Boiler.ID)] <- T
  bga.3.2$unmapped[!is.na(bga.3.2$Boiler.ID)] <- F
  
  if (analysisYear>2003){
  bga.3.2$Unit.Code[is.na(bga.3.2$Unit.Code)] <- "none"
}
  
  Boiler.ID_NotAssoc<-dplyr::anti_join(Boiler.ID_NotAssoc,bga.3.2, by=c("Plant.Code","Boiler.ID"))
  bga.3.3 <- bga.3.2 %>% dplyr::select(-c(".merge"))
  
  bga.out=bga.3.3

  

  if (printStatus){message("Making fillwithGenID matches")}
    bga.out$bga.source[is.na(bga.out$Boiler.ID)] <- "fillwithGenID"
    bga.out$Boiler.ID[is.na(bga.out$Boiler.ID)] <- bga.out$Generator.ID[is.na(bga.out$Boiler.ID)]
  
  
  #orphan Boilers
  Boiler.ID_NotAssoc<-dplyr::anti_join(Boiler.ID_NotAssoc,bga.out,by=c("Plant.Code","Boiler.ID"))

  bga.out$Orphan.Boiler<-FALSE
  orphanBoilers<-Boiler.ID_NotAssoc %>% dplyr::filter(!is.na(Boiler.ID_NotAssoc$Boiler.ID))
  orphanBoilers2<-merge(orphanBoilers[,!names(orphanBoilers) %in% names(bfd.923)[!names(bfd.923) %in% c("Plant.Code","Boiler.ID")]],
                        bfd.923, by=c("Plant.Code","Boiler.ID"), all=TRUE)
  orphanBoilers<-dplyr::anti_join(orphanBoilers,orphanBoilers2, by=c("Plant.Code","Boiler.ID"))
  orphanBoilers<-rbind(orphanBoilers,orphanBoilers2)
 
  if (analysisYear>2005){
  fillOrphanBoilers<-bga.out[0,]
  for (o in unique(orphanBoilers$Plant.Code)){
    subBGA<-bga.out %>% dplyr::filter(Plant.Code==o)
    subOrphan<-orphanBoilers %>% dplyr::filter(Plant.Code==o) 
    subOrphan<-subOrphan %>% dplyr::select(names(subOrphan)[names(subOrphan) %in% names(subBGA)])
                            
    for (b in 1:length(subOrphan$Boiler.ID)){
      subBoil<-subOrphan[b,]
      if (!is.na(subBoil$Reported.Prime.Mover_bf.923)){
      if (subBoil$Reported.Prime.Mover_bf.923=="CS"){
        if (subBoil$Boiler.ID %in% stats::na.omit(bga.out$Generator.ID)){
          namevector<-names(subBGA)[!names(subBGA) %in% names(subBoil)]
          fillOut <- do.call("cbind", list(subBoil, rep(list(NA),length(namevector))))
          colnames(fillOut)[-1*(1:(ncol(fillOut) - length(namevector)))] <- namevector
          fillOut$Generator.ID<-fillOut$Boiler.ID
          fillOut$Orphan.Boiler<-TRUE
          fillOut<-fillOut %>% dplyr::select(names(subBGA))
          fillOrphanBoilers<-rbind(fillOrphanBoilers,fillOut)
          
        }#if Boiler.ID in Generator.IDs
        
      }#if CS Prime Mover
      }#if !is.n Prime Mover
    }#for each Boiler.ID
  }#for each Plant in orphan Boilers


  
  bga.out<-dplyr::anti_join(bga.out,fillOrphanBoilers,by=c("Plant.Code","Boiler.ID"))
  bga.out<-rbind(bga.out,fillOrphanBoilers)
  }#analysisYear>2005
  
  Boiler.ID_NotAssoc<-dplyr::anti_join(Boiler.ID_NotAssoc,bga.out,by=c("Plant.Code","Boiler.ID"))
  Boiler.ID_NotAssoc<- Boiler.ID_NotAssoc %>% dplyr::select(names(Boiler.ID_NotAssoc)[names(Boiler.ID_NotAssoc) 
                                                                               %in% names(bga.out)])

  
  if (printStatus){message("Joining with boilerDesignData table")}
  #add Boiler.Status column
  boilerDesignData<-formatIDcol(boilerDesignData,idCol="Boiler.ID",
                    flagColname = "flagBoiler.ID_boilerDesignData",
                    originalColname="orig_Boiler.ID_boilerDesignData")

  if (analysisYear<=2005){
    boilerDesignData$Retirement.Date<-as.POSIXct(boilerDesignData$Retirement.Date,format="%Y-%m-%d")
    boilerDesignData$Retirement.Year<-as.integer(format(boilerDesignData$Retirement.Date,format="%Y"))
    boilerDesignData$Retirement.Month<-as.integer(format(boilerDesignData$Retirement.Date,format="%m"))
  }
  boilerDesignData<-boilerDesignData %>% dplyr::select("Plant.Code","Boiler.ID","Boiler.Status","Retirement.Year","Retirement.Month")
  names(boilerDesignData)<-c("Plant.Code","Boiler.ID","Boiler.Status","Boiler.Retirement.Year","Boiler.Retirement.Month")
  bga.out<-merge(bga.out,boilerDesignData,by=c("Plant.Code","Boiler.ID"),all.x=T)
  bga.out<-bga.out %>% dplyr::mutate(flag_BoilerRetired = ifelse(Boiler.Retirement.Year<analysisYear & Boiler.Retirement.Year!=0,1,0))
  bga.out<-bga.out %>% dplyr::mutate(flag_Boiler.Status = ifelse(Boiler.Status %in% c("OS","OA","RE") & is.na(orig_Boiler.ID_bf.923),1,0))
  
  #add flag_Generator.Status
  bga.out<-bga.out %>% dplyr::mutate(flag_Generator.Status = ifelse(Generator.Status %in% c("OS","OA") & 
                                                               (is.na(orig_Generator.ID_923) | Net.Generation.mwh==0),1,0))
  if (printStatus){message("Joining with retiredGenerator table")}
  #flag retired Generators
  retiredGenerators<-formatIDcol(retiredGenerators,idCol="Generator.ID",
                                flagColname = "flagGenerator.ID_retiredGenerators",
                                originalColname="orig_Generator.ID_retiredGenerator")
  
  retiredGenerators<-retiredGenerators %>% dplyr::select("Plant.Code","Generator.ID","Retirement.Year","Retirement.Month")
  names(retiredGenerators)<-c("Plant.Code","Generator.ID","Generator.Retirement.Year","Generator.Retirement.Month")
  bga.out<-merge(bga.out,retiredGenerators,by=c("Plant.Code","Generator.ID"),all.x=T)
  bga.out<-bga.out %>% dplyr::mutate(flag_GeneratorRetired = ifelse(Generator.Retirement.Year<analysisYear & Generator.Retirement.Year!=0,1,0))
  
  
  #add flag Boiler.ID not is association table
  bga.out$Boiler.ID.NotIn.Assoc<-ifelse(is.na(bga.out$orig_Boiler.ID_assoc),1,0)
  
  #add flag missing plant from table
  bga.out<-merge(bga.out,missingPlants, by="Plant.Code",all.x=T)

  
  bga.out.for.associate <- bga.out %>% dplyr::filter(!is.na(Plant.Code))
  bga.out.for.associate$Boiler.ID<-sapply(bga.out.for.associate$Boiler.ID, function(x) ifelse(is.na(x),"NA",x))


 bga.out.for.associate.sort<-bga.out.for.associate[c(1:3)]
 bga.out.for.associate.sort<-bga.out.for.associate.sort %>%
dplyr::arrange(Plant.Code,nchar(Boiler.ID),Boiler.ID,nchar(Generator.ID),Generator.ID)

 bga.out.for.associate.sort<-bga.out.for.associate.sort[!duplicated(bga.out.for.associate.sort),]
 
 #flag floating generators
 if (printStatus){message("Checking for flag_floatingGen")}
 # if gen.id %in% boil.id AND no row exists with gen.id=boil.id
 checkPlants<-integer(0)
 for (p in unique(bga.out.for.associate.sort$Plant.Code)){
   dfSub<-bga.out.for.associate.sort[bga.out.for.associate.sort$Plant.Code==p,c("Boiler.ID","Generator.ID")]
   testGen<-unique(dfSub$Generator.ID)
   for (g in testGen){
     if (g %in% unique(dfSub$Boiler.ID)){
       bSub<-dfSub[dfSub$Boiler.ID==g & dfSub$Generator.ID==g,]
       if (nrow(bSub)==0){#floating generator
         checkPlants<-c(checkPlants,p)
         bga.out.for.associate.sort[bga.out.for.associate.sort$Plant.Code==p & 
                                      bga.out.for.associate.sort$Generator.ID==g,]$Generator.ID<-paste0(bga.out.for.associate.sort[bga.out.for.associate.sort$Plant.Code==p & 
                                                                                                                                     bga.out.for.associate.sort$Generator.ID==g,]$Generator.ID,"_floatingGen")
       }#if floating
     }#if g in Boiler.IDs
   }#for each gen
 }#for each plant
 checkPlants<-unique(checkPlants)
 

 
 bga.out.for.associate.sort<-bga.out.for.associate.sort[!is.na(bga.out.for.associate.sort$Generator.ID),]
 
    #Generates concatenated bogen code used for summaries according to Bogen.
 if (printStatus){message("Running associations")}
  out <- associate(bga.out.for.associate.sort,associationType = "bogen")
  
  #Merge the Bogen code with the Bogen associations data frame to create Bogen key used in 
  #analysis
  data.out <- dplyr::left_join(out,bga.out, by=c("Plant.Code","Boiler.ID"))

  
  if (analysisYear>2005){
   data.out <- data.out %>% dplyr::filter(Reported.Prime.Mover_860 %in% stats::na.omit(select_RPM) |
                                  Reported.Prime.Mover_923 %in% stats::na.omit(select_RPM) |
                                  Reported.Prime.Mover_bf.923 %in% stats::na.omit(select_RPM))
  na.Boiler.ID <- na.Boiler.ID %>% dplyr::filter(Reported.Prime.Mover_860 %in% stats::na.omit(select_RPM) |
                                    Reported.Prime.Mover_923 %in% stats::na.omit(select_RPM) |
                                    Reported.Prime.Mover_bf.923 %in% stats::na.omit(select_RPM)) 
  }else{
    data.out <- data.out %>% dplyr::filter(Reported.Prime.Mover_860 %in% stats::na.omit(select_RPM))
    na.Boiler.ID <- na.Boiler.ID %>% dplyr::filter(Reported.Prime.Mover_860 %in% stats::na.omit(select_RPM)) 
  }

  if (printStatus){message("Testing for missing Fuel Consumption and/or Net Generation data")}
  #test for missing CS/CT data in Page3 or Page4
  gen_fuel_data<-gen_fuel_data %>% dplyr::filter(Plant.Code %in% plantList)
  gen_fuel_data<-gen_fuel_data %>% dplyr::filter(Reported.Prime.Mover %in% stats::na.omit(select_RPM))
  gen_fuel_data<-gen_fuel_data %>% dplyr::filter((is.na(Nuclear.Unit.Id) | Nuclear.Unit.Id=="."))
  
  #check for decembrists
  decembrist<-checkDecember(FuelHeatByLine=bf.923.ungrouped,NetGenByLine=generation.data.line124,
                            gen_fuel_data,plantList,select_RPM)
  
  #check for missing NGCC data
  missingCSCT<-checkMissingCSCT(gen_923, bf.923.ungrouped,gen_fuel_data, analysisYear)
  #set NGCC bogen for plants missing data on Page1
  if (analysisYear==2014){
  anyMissingNGCC<-checkANYmissingNGCC(generation.data.line124, boilerFuelData,gen_fuel_data, analysisYear)
  }else{
    anyMissingNGCC<-numeric(0)
  }
  #remove if missingCSCT
  data.out<-data.out %>% dplyr::filter(!(Plant.Code %in% missingCSCT$Plant.Code & 
                                    (Reported.Prime.Mover_860 %in% c("CS","CT","CA")| 
                                       Reported.Prime.Mover_923 %in% c("CS","CT","CA") | 
                                       Reported.Prime.Mover_bf.923 %in% c("CS","CT","CA"))))
  #save gen_fuel_data
  gen_fuel_data_all<-gen_fuel_data
  
  #Calculate Fuel.Heat and NetGen from Page 1 for missingCSCT
  gen_fuel_data<-gen_fuel_data %>% dplyr::filter(Plant.Code %in% missingCSCT$Plant.Code)
  gen_fuel_data<-gen_fuel_data %>% dplyr::filter(Reported.Prime.Mover %in% c("CS","CT","CA"))
  
  #get Plant-RPM sums
  
  sum.list<-sumGenFuelData(gen_fuel_data,bf.923.ungrouped, 
                                generation.data.line124,analysisYear)
  list2env(sum.list,envir = myEnv)
  gen_fuel_data<-sum.list$gen_fuel_data
  assign("bf.923.ungrouped",sum.list$bf.923.ungrouped,envir = parent.frame())
  assign("generation.data.line124",sum.list$generation.data.line124,envir = parent.frame())
  
  #add plant-RPM level Bogen
  gen_fuel_data$Bogen<-rep("",nrow(gen_fuel_data))
  for (p in unique(gen_fuel_data$Plant.Code)){
    gen_fuel_data[which(gen_fuel_data$Plant.Code==p),]$Bogen<-paste0(p,"^","NGCC")
  }
  
  data.out<-plyr::rbind.fill(data.out,gen_fuel_data)
  data.out<-data.out[order(data.out$Plant.Code,data.out$Bogen),]
  
  #decembrists sums
  #remove if decembrist
  data.out<-data.out %>% dplyr::filter(!Plant.Code %in% decembrist)
  gen_fuel_data<-gen_fuel_data_all
  gen_fuel_data<-gen_fuel_data %>% dplyr::filter(Plant.Code %in% decembrist)
  gen_fuel_data<-gen_fuel_data %>% dplyr::filter(Reported.Prime.Mover %in% stats::na.omit(select_RPM))
  gen_fuel_data$Reported.Prime.Mover<-ifelse(gen_fuel_data$Reported.Prime.Mover %in% c("CS","CT","CA"),"NGCC",
                                             gen_fuel_data$Reported.Prime.Mover)
  #get Plant-RPM sums
  sum.list<-sumGenFuelData(gen_fuel_data,bf.923.ungrouped, 
                           generation.data.line124,analysisYear)
  list2env(sum.list,envir = myEnv)
  gen_fuel_data<-sum.list$gen_fuel_data
  assign("bf.923.ungrouped",sum.list$bf.923.ungrouped,envir = parent.frame())
  assign("generation.data.line124",sum.list$generation.data.line124,envir = parent.frame())
  
  #add PLant-RPM-level Bogen
  if (printStatus){message("Creating Plant-Reported.Prime.Mover level bogens")}
  gen_fuel_data$Bogen<-rep("",nrow(gen_fuel_data))
  for (p in unique(gen_fuel_data$Plant.Code)){
    gen_fuel_data[which(gen_fuel_data$Plant.Code==p),]$Bogen<-paste0(p,"^",
                              gen_fuel_data[which(gen_fuel_data$Plant.Code==p),]$Reported.Prime.Mover_page1)
  }
  
  data.out<-plyr::rbind.fill(data.out,gen_fuel_data)
  data.out<-data.out[order(data.out$Plant.Code,data.out$Bogen),]
  

  #remove if anyMissingNGCC
  data.out<-data.out %>% dplyr::filter(!(Plant.Code %in% anyMissingNGCC & 
                                    (Reported.Prime.Mover_860 %in% c("CS","CT","CA")| 
                                       Reported.Prime.Mover_923 %in% c("CS","CT","CA") | 
                                       Reported.Prime.Mover_bf.923 %in% c("CS","CT","CA"))))
  #save gen_fuel_data
  gen_fuel_data<-gen_fuel_data_all
  
  #Calculate Fuel.Heat and NetGen from Page 1 for missingCSCT
  gen_fuel_data<-gen_fuel_data %>% dplyr::filter(Plant.Code %in% anyMissingNGCC)
  gen_fuel_data<-gen_fuel_data %>% dplyr::filter(Reported.Prime.Mover %in% c("CS","CT","CA"))
  
  #get Plant-RPM sums 
  sum.list<-sumGenFuelData(gen_fuel_data,bf.923.ungrouped, 
                           generation.data.line124,analysisYear)
  list2env(sum.list,envir = myEnv)
  gen_fuel_data<-sum.list$gen_fuel_data
  assign("bf.923.ungrouped",sum.list$bf.923.ungrouped,envir = parent.frame())
  assign("generation.data.line124",sum.list$generation.data.line124,envir = parent.frame())

  
  #add plant-level Bogen
  gen_fuel_data$Bogen<-rep("",nrow(gen_fuel_data))
  for (p in unique(gen_fuel_data$Plant.Code)){
    gen_fuel_data[which(gen_fuel_data$Plant.Code==p),]$Bogen<-paste0(p,"^","NGCC")
  }
  
  data.out<-plyr::rbind.fill(data.out,gen_fuel_data)
  data.out<-data.out[order(data.out$Plant.Code,data.out$Bogen),]
  
  


  #flag missing from ST and BoilerFuelData.923
  data.out$missing.bf.923<-ifelse(is.na(data.out$orig_Boiler.ID_bf.923) & 
                                    (is.na(data.out$missing.bf.923) | data.out$missing.bf.923==TRUE) ,TRUE,FALSE)
  if (analysisYear>2005){
    data.out<-data.out %>% dplyr::mutate(flag.ST.missing.bf.923=ifelse((Reported.Prime.Mover_923=="ST" | 
                                                                 Reported.Prime.Mover_860=="ST") &
                                                                missing.bf.923==TRUE,1,0))
  }else{
    data.out<-data.out %>% dplyr::mutate(flag.ST.missing.bf.923=ifelse((Reported.Prime.Mover_860=="ST") &
                                                                  missing.bf.923==TRUE,1,0))
    }
  

 
   #remove if missing.from.923
  data.out<-data.out %>% dplyr::filter((missing.from.923==FALSE | is.na(missing.from.923)) | regexpr("NGCC",Bogen)>0 | regexpr("ST",Bogen)<0)
  data.out$missing.from.923<-ifelse(is.na(data.out$missing.from.923) & regexpr("NGCC",data.out$Bogen)<0 & regexpr("ST",data.out$Bogen)<0,
                                    FALSE,data.out$missing.from.923)

  if (printStatus){message("Check for missing CA-CT pairs (flag.CACT.missingPair)")}
  #check if any bogen CA without CT
  data.out$flag.CACT.missingPair<-FALSE
  data.out$flag_923bogenCTonly<-FALSE
  for (b in as.character(unique(data.out[regexpr("NGCC",data.out$Bogen)<0 & regexpr("ST",data.out$Bogen)<0,]$Bogen))){
    subData<-data.out %>% dplyr::filter(Bogen==b)
    if (analysisYear>2005){
      allRPMs<-as.character(unique(c(subData$Reported.Prime.Mover_860,
                      subData$Reported.Prime.Mover_923,
                      subData$Reported.Prime.Mover_bf.923,
                      subData$Reported.Prime.Mover_page1)))
    }else{
      allRPMs<-as.character(unique(c(subData$Reported.Prime.Mover_860,
                                     subData$Reported.Prime.Mover_page1)))
    }
    
    if (analysisYear>2005){
      RPMs.923<-as.character(unique(c(subData$Reported.Prime.Mover_923,
                                   subData$Reported.Prime.Mover_bf.923,
                                   subData$Reported.Prime.Mover_page1)))
    }
   
    if ("CT" %in% allRPMs & !"CA" %in% allRPMs){
      data.out[data.out$Bogen==b,]$flag.CACT.missingPair<-rep(TRUE,nrow(data.out[data.out$Bogen==b,]))
    }else if ("CA" %in% allRPMs & !"CT" %in% allRPMs){
      data.out[data.out$Bogen==b,]$flag.CACT.missingPair<-rep(TRUE,nrow(data.out[data.out$Bogen==b,]))
    }
   
   #check if ONLY 'CT' in923 RPMS
    if(analysisYear>2005){
   if (length(unique(RPMs.923))==1 & !identical(unique(RPMs.923),NA)){
     if(identical(as.character(unique(RPMs.923)),"CT")){
       data.out[data.out$Bogen==b,]$flag_923bogenCTonly<-rep(TRUE,nrow(data.out[data.out$Bogen==b,]))
     }
   }
    }#analysisYear>2005
  }
 
  if (printStatus){message("Check for questionable fuel types assigned to NGCC plants (flag.NGCC.badFuel)")}
  if (analysisYear>2005){
  Reported.Prime.Mover_cols <- c("Reported.Prime.Mover_860","Reported.Prime.Mover_923","Reported.Prime.Mover_bf.923","Reported.Prime.Mover_page1")
  }else{
    Reported.Prime.Mover_cols <- c("Reported.Prime.Mover_860","Reported.Prime.Mover_page1")
  }

  badFuels<-checkBadFuel(data.out,Reported.Prime.Mover_cols)
   data.out$flag.NGCC.badFuel<-ifelse(data.out$Plant.Code %in% badFuels,1,0)
  
  #count rows per Plant
  countRows<-data.out %>% dplyr::group_by(Plant.Code) %>% dplyr::count(Plant.Code)
  data.out<-merge(data.out,countRows, by="Plant.Code")
  
  #flag for removal if flag.ST.missing.bf.923 & countRows!=1 | unmapped!=TRUE
  data.out$flag.ST.missing.bf.923.unmapped<-ifelse(data.out$flag.ST.missing.bf.923==1 & 
                                                     (data.out$n!=1 | data.out$unmapped!=TRUE) & 
                                                     regexpr("NGCC",data.out$Bogen)<0 & 
                                                     regexpr("ST",data.out$Bogen)<0,1,0)
  data.out<-data.out %>% dplyr::select(-n)

  #add inconsistent RPM flag
  if (analysisYear>2005){
  data.out<-merge(data.out, compare_RPM %>% dplyr::select(Plant.Code,Generator.ID,flag_RPM), 
                  by=c("Plant.Code","Generator.ID"), all.x=TRUE)
  }
  
  #add floating generator flag
  data.out<-data.out %>% dplyr::mutate(flag_floatingGen=ifelse(Plant.Code %in% checkPlants,1,0))
  
   #Additional Fuel Heat Calculations added 9.29.21
  if (printStatus){message("Summing by Fuel Heat and Net Generation by bogen")}
  #Sum by Bogen
  uniqueFuelHeat<-data.out %>% dplyr::select(c("Plant.Code","Boiler.ID","Bogen"),dplyr::contains("Fuel.Heat"))
  uniqueFuelHeat<-uniqueFuelHeat[!duplicated(uniqueFuelHeat),]
 
  for(m in months){
    fuelHeatstr<-paste0("uniqueFuelHeat<-uniqueFuelHeat %>% dplyr::mutate(Boiler.ID.Total.Fuel.Heat.",m," = ifelse(regexpr('NGCC',Bogen)>0 | regexpr('ST',Bogen)>0,
                                                            PlantLine.Total.Fuel.Heat.",m,",Boiler.ID.Total.Fuel.Heat.",m,"))")
    eval(parse(text=fuelHeatstr))
    fuelHeatstr<-paste0("sumbyBogen<-uniqueFuelHeat %>% dplyr::group_by(Plant.Code,Bogen) %>% 
                        dplyr::summarize(Bogen.Total.Fuel.Heat.",m,"=sum(Boiler.ID.Total.Fuel.Heat.",m,",na.rm=T))")
    eval(parse(text=fuelHeatstr))
    if (m=="January"){
      sumFuelHeatByBogen<-sumbyBogen  
    }else{
      
      sumFuelHeatByBogen<-merge(sumFuelHeatByBogen,sumbyBogen,by=c("Plant.Code","Bogen"),all=T)
    }
    
  }
  assign("sumFuelHeatByBogen",sumFuelHeatByBogen,envir = parent.frame())
  #Sum by Plant by summing Bogens
  for(m in months){
    fuelHeatstr<-paste0("sumbyPlant<-sumFuelHeatByBogen %>% dplyr::group_by(Plant.Code) %>% 
                        dplyr::summarize(Plant.Total.Fuel.Heat.",m,"=sum(Bogen.Total.Fuel.Heat.",m,",na.rm=T))")
    eval(parse(text=fuelHeatstr))
    if (m=="January"){
      sumFuelHeatBogensByPlant<-sumbyPlant  
    }else{
      
      sumFuelHeatBogensByPlant<-merge(sumFuelHeatBogensByPlant,sumbyPlant,by=c("Plant.Code"),all=T)
    }
    
  }

  
  ###########################
  #Additional NetGen Calculations added 3.1.22
  #Sum by Bogen
  uniqueNetGen<-data.out %>% dplyr::select(c("Plant.Code","Generator.ID","Bogen"),
                                    dplyr::contains("Generator.ID.Total.Net.Generation"),
                                    dplyr::contains("PlantLine.Total.Net.Generation."))
  uniqueNetGen<-uniqueNetGen[!duplicated(uniqueNetGen),]
  for(m in months){
    netGenstr<-paste0("uniqueNetGen<-uniqueNetGen %>% dplyr::mutate(Generator.ID.Total.Net.Generation.",m," = ifelse(regexpr('NGCC',Bogen)>0 | regexpr('ST',Bogen)>0,
                                                            PlantLine.Total.Net.Generation.",m,",Generator.ID.Total.Net.Generation.",m,"))")
    eval(parse(text=netGenstr))
    netGenstr<-paste0("sumbyBogen<-uniqueNetGen %>% dplyr::group_by(Plant.Code,Bogen) %>% 
                        dplyr::summarize(Bogen.Total.Net.Generation.",m,"=sum(Generator.ID.Total.Net.Generation.",m,",na.rm=T))")
    eval(parse(text=netGenstr))
    if (m=="January"){
      sumNetGenByBogen<-sumbyBogen  
    }else{
      
      sumNetGenByBogen<-merge(sumNetGenByBogen,sumbyBogen,by=c("Plant.Code","Bogen"),all=T)
    }
    
  }
  assign("sumNetGenByBogen",sumNetGenByBogen,envir = parent.frame())
  #Sum by Plant by summing Bogens
  for(m in months){
    netGenstr<-paste0("sumbyPlant<-sumNetGenByBogen %>% dplyr::group_by(Plant.Code) %>% 
                        dplyr::summarize(Plant.Total.Net.Generation.",m,"=sum(Bogen.Total.Net.Generation.",m,",na.rm=T))")
    eval(parse(text=netGenstr))
    if (m=="January"){
      sumNetGenBogensByPlant<-sumbyPlant  
    }else{
      
      sumNetGenBogensByPlant<-merge(sumNetGenBogensByPlant,sumbyPlant,by=c("Plant.Code"),all=T)
    }
    
  }
 
  if (printStatus){message("Calculating Thermal Efficiency by bogen")}
  #thermal Effficiency
 thermalEffByBogen<-dplyr::inner_join(sumNetGenByBogen,sumFuelHeatByBogen,by=c("Plant.Code","Bogen"))
 for (m in months){
   eval(parse(text=paste0("thermalEffByBogen<-thermalEffByBogen %>% dplyr::mutate(ThermalEfficiency.",m,"=3.41214*Bogen.Total.Net.Generation.",m,"/
                       Bogen.Total.Fuel.Heat.",m,")")))
   eval(parse(text=paste0("thermalEffByBogen<-thermalEffByBogen %>% dplyr::mutate(ThermalEfficiency.",m,"=ifelse(Bogen.Total.Net.Generation.",m,"
                       <=0 & Bogen.Total.Fuel.Heat.",m,"<=0,0,ifelse(Bogen.Total.Net.Generation.",m,">0 & Bogen.Total.Fuel.Heat.",m,"<=0,
                          9999,ThermalEfficiency.",m,")))")))
   
 }
 assign("thermalEffByBogen",thermalEffByBogen,envir = parent.frame())
 
  ############################
  
  #flag PLant Level NetGen>0 and FuelHet<=0 monthly
  compareNetGenFuelHeat<-merge(sumNetGenBogensByPlant,sumFuelHeatBogensByPlant,by="Plant.Code")
  compareNetGenFuelHeat$flagNetGenWithoutFuelHeat<-rep(0,nrow(compareNetGenFuelHeat))
  for(m in months){

    flagstr<-paste0("compareNetGenFuelHeat<-compareNetGenFuelHeat %>% dplyr::mutate(flagNetGenWithoutFuelHeat=ifelse(
                        Plant.Total.Fuel.Heat.",m,"<=0 & Plant.Total.Net.Generation.",m,">0,
                    flagNetGenWithoutFuelHeat+1,flagNetGenWithoutFuelHeat))")
    eval(parse(text=flagstr))  
    flagstr<-paste0("compareNetGenFuelHeat<-compareNetGenFuelHeat %>%
                    dplyr::mutate(flagNG_no_FH_",m,"=ifelse(Plant.Total.Fuel.Heat.",m,"<=0 & 
                    Plant.Total.Net.Generation.",m,">0,1,0))")
    eval(parse(text=flagstr))    
  }

  #add flagNetGenWithoutFuelHeat flag
  data.out<-merge(data.out, compareNetGenFuelHeat %>% dplyr::select(Plant.Code,
                                                             flagNetGenWithoutFuelHeat,
                                                             dplyr::contains("flagNG_no_FH_")), 
                  by=c("Plant.Code"), all.x=TRUE)
  
  #flag Bogen Level NetGen<0 and FuelHet>0 monthly
  compareNetGenFuelHeat<-merge(sumNetGenByBogen,sumFuelHeatByBogen,by=c("Plant.Code","Bogen"))
  compareNetGenFuelHeat$flagFuelHeatWithoutNetGen<-rep(0,nrow(compareNetGenFuelHeat))
  for(m in months){
    flagstr<-paste0("compareNetGenFuelHeat<-compareNetGenFuelHeat %>% dplyr::mutate(flagFuelHeatWithoutNetGen=ifelse(
                        Bogen.Total.Fuel.Heat.",m,">0 & Bogen.Total.Net.Generation.",m,"<0,flagFuelHeatWithoutNetGen+1,flagFuelHeatWithoutNetGen))")
    eval(parse(text=flagstr))
    flagstr<-paste0("compareNetGenFuelHeat<-compareNetGenFuelHeat %>%
                    dplyr::mutate(flagFH_no_NG_",m,"=ifelse(Bogen.Total.Fuel.Heat.",m,">0 & 
                    Bogen.Total.Net.Generation.",m,"<0,1,0))")
    eval(parse(text=flagstr)) 
  }
  #add flagNetGenWithoutFuelHeat flag
  data.out<-merge(data.out, compareNetGenFuelHeat %>% dplyr::select(Plant.Code,Bogen,
                                                             flagFuelHeatWithoutNetGen, 
                                                             dplyr::contains("flagFH_no_NG_")), 
                  by=c("Plant.Code","Bogen"), all.x=TRUE)
  

  #compare sumFuelHeatBogensByPlant and sumFuelHeatLinesByPlant -> Manual Flag
  compareTotFuelHeat<-merge(sumFuelHeatBogensByPlant,sumFuelHeatLinesByPlant, by="Plant.Code")
  compareTotFuelHeat$flagFuelHeat<-rep(0,nrow(compareTotFuelHeat))
  for(m in months){
    fuelHeatstr<-paste0("compareTotFuelHeat<-compareTotFuelHeat %>% dplyr::mutate(flagFuelHeat=ifelse(
                        round(Plant.Total.Fuel.Heat.",m,",3)==round(PlantLine.Total.Fuel.Heat.",m,",3),
                        flagFuelHeat,flagFuelHeat+1))")
    eval(parse(text=fuelHeatstr))
    fuelHeatstr<-paste0("compareTotFuelHeat<-compareTotFuelHeat %>% dplyr::mutate(flagFuelHeat_",m,"=ifelse(
                        round(Plant.Total.Fuel.Heat.",m,",3)==round(PlantLine.Total.Fuel.Heat.",m,",3),
                        0,1))")
    eval(parse(text=fuelHeatstr))
  }

  #add flagFuelHeat flag
 data.out<-merge(data.out, compareTotFuelHeat %>% dplyr::select(Plant.Code,dplyr::contains("flagFuelHeat")), 
                              by=c("Plant.Code"), all.x=TRUE)
 
 if (printStatus){message("Creating flag_STassoc_CT_CS_CA")}
 #flag ST associated with CT,CS,CA
 data.out$flag_STassoc_CT_CS_CA<-rep(0,nrow(data.out))
 dataFlag.out<-data.out[0,]
 for (b in unique(data.out$Bogen)){
   subdata.out<-data.out %>% dplyr::filter(Bogen==b)
   if (analysisYear>2005){
     allRPMs<-as.character(unique(c(subdata.out$Reported.Prime.Mover_860,
                                    subdata.out$Reported.Prime.Mover_923,
                                    subdata.out$Reported.Prime.Mover_bf.923,
                                    subdata.out$Reported.Prime.Mover_page1)))
   }else{
     allRPMs<-c(unique(subdata.out$Reported.Prime.Mover_860,
                       subdata.out$Reported.Prime.Mover_page1))
   }
   if ("ST" %in% allRPMs &
       ("CT" %in% allRPMs |
        "CS" %in% allRPMs |
        "CA" %in% allRPMs
        )){
     subdata.out$flag_STassoc_CT_CS_CA<-rep(1,nrow(subdata.out))
     
   }
   dataFlag.out<-rbind(dataFlag.out,subdata.out)
 }
 data.out<-dataFlag.out

 if (printStatus){message("Creating flag_CSassociation")}
 #flag CS associated anything
 data.out$flag_CSassociation<-rep(0,nrow(data.out))
 dataFlag.out<-data.out[0,]
 for (b in unique(data.out$Bogen)){
   subdata.out<-data.out %>% dplyr::filter(Bogen==b)
   if (analysisYear>2005){
     allRPMs<-as.character(unique(c(subdata.out$Reported.Prime.Mover_860,
                       subdata.out$Reported.Prime.Mover_923,
                       subdata.out$Reported.Prime.Mover_bf.923,
                       subdata.out$Reported.Prime.Mover_page1)))
   }else{
     allRPMs<-c(unique(subdata.out$Reported.Prime.Mover_860,
                       subdata.out$Reported.Prime.Mover_page1))
   }
   if ("CS" %in% allRPMs &
       length(unique(stats::na.omit(allRPMs)))!=1
       ){
     subdata.out$flag_CSassociation<-rep(1,nrow(subdata.out))
     
   }
   dataFlag.out<-rbind(dataFlag.out,subdata.out)
 }
 data.out<-dataFlag.out
 

  #add countFlags column
  countFlagfunc<-function(f){
    if (!is.na(f)){
    if(f==TRUE | f>=1 | f %in% c("OS","OA","RE")){
      c<-1
    }else{#no flag
      c<-0
    }
    }else{#missing flag
      c<-0
    }
    return(c)
  }
  
  if (analysisYear>2005){
    countFlagstr<-"data.out<-data.out %>% dplyr::rowwise() %>% dplyr::mutate(countFlags = sum(countFlagfunc(missing.from.923),
                                                 countFlagfunc(Generator.Status),
                                                 countFlagfunc(Orphan.Generator),
                                                 countFlagfunc(unmapped_but_in_923),
                                                 countFlagfunc(unmapped),
                                                 countFlagfunc(Orphan.Boiler),
                                                 countFlagfunc(Boiler.Status),
                                                 countFlagfunc(Boiler.ID.NotIn.Assoc),
                                                 countFlagfunc(missingPlant.assoc),
                                                 countFlagfunc(missingPlant.generator.data.860),
                                                 countFlagfunc(missingPlant.boilerDesignData.860),
                                                 countFlagfunc(missingPlant.generation.data.923),
                                                 countFlagfunc(missingPlant.boilerFuelData.923),
                                                 countFlagfunc(flag.CACT.missingPair),
                                                 countFlagfunc(missing.bf.923),
                                                 countFlagfunc(flag.ST.missing.bf.923),
                                                 countFlagfunc(flag.ST.missing.bf.923.unmapped),
                                                 countFlagfunc(flag_RPM),
                                                 countFlagfunc(flag_floatingGen),
                                                 countFlagfunc(flag_BoilerRetired),
                                                 countFlagfunc(flag_Boiler.Status),
                                                 countFlagfunc(flag_GeneratorRetired),
                                                 countFlagfunc(flag_Generator.Status),
                                                 countFlagfunc(flag_923bogenCTonly),
                                                 countFlagfunc(flagFuelHeat),
                                                 countFlagfunc(flag_STassoc_CT_CS_CA),
                                                 countFlagfunc(flag_CSassociation),
                                                 countFlagfunc(flagNetGenWithoutFuelHeat),
                                                 countFlagfunc(flagFuelHeatWithoutNetGen),
                                                 countFlagfunc(flag.NGCC.badFuel),"
  }else{
  countFlagstr<-"data.out<-data.out %>% dplyr::rowwise() %>% dplyr::mutate(countFlags = sum(countFlagfunc(missing.from.923),
                                                 countFlagfunc(Generator.Status),
                                                 countFlagfunc(Orphan.Generator),
                                                 countFlagfunc(unmapped_but_in_923),
                                                 countFlagfunc(unmapped),
                                                 countFlagfunc(Orphan.Boiler),
                                                 countFlagfunc(Boiler.Status),
                                                 countFlagfunc(Boiler.ID.NotIn.Assoc),
                                                 countFlagfunc(missingPlant.assoc),
                                                 countFlagfunc(missingPlant.generator.data.860),
                                                 countFlagfunc(missingPlant.boilerDesignData.860),
                                                 countFlagfunc(missingPlant.generation.data.923),
                                                 countFlagfunc(missingPlant.boilerFuelData.923),
                                                 countFlagfunc(flag.CACT.missingPair),
                                                 countFlagfunc(missing.bf.923),
                                                 countFlagfunc(flag.ST.missing.bf.923),
                                                 countFlagfunc(flag.ST.missing.bf.923.unmapped),
                                                 countFlagfunc(flag_floatingGen),
                                                 countFlagfunc(flag_BoilerRetired),
                                                 countFlagfunc(flag_Boiler.Status),
                                                 countFlagfunc(flag_GeneratorRetired),
                                                 countFlagfunc(flag_Generator.Status),
                                                 countFlagfunc(flagFuelHeat),
                                                 countFlagfunc(flag_STassoc_CT_CS_CA),
                                                 countFlagfunc(flag_CSassociation),
                                                 countFlagfunc(flagNetGenWithoutFuelHeat),
                                                 countFlagfunc(flagFuelHeatWithoutNetGen),"
  }
  for (m in months){
    if (m!="December"){
    countFlagstr<-paste0(countFlagstr,"countFlagfunc(flagFH_no_NG_",m,"),
                                      countFlagfunc(flagNG_no_FH_",m,"),
                                      countFlagfunc(flagFuelHeat_",m,"),")
    }else{
      countFlagstr<-paste0(countFlagstr,"countFlagfunc(flagFH_no_NG_",m,"),
                                      countFlagfunc(flagNG_no_FH_",m,"),
                                      countFlagfunc(flagFuelHeat_",m,")))")
    }
  }
  eval(parse(text=countFlagstr))
    
  
                                                 
  if (printStatus){message("Finding plants selected for manual bogen checks")}
  #manual Plants
  flagCTCA_plants<-data.out %>% dplyr::filter(flag.CACT.missingPair==1)
  flagCTCA_plants<-data.frame(Plant.Code = unique(flagCTCA_plants$Plant.Code),
                              flag.CACT.missingPair = rep(1,length(unique(flagCTCA_plants$Plant.Code))))
  manualPlants<-flagCTCA_plants
  

  flag_923bogenCTonly_plants<-data.out %>% dplyr::rowwise() %>% dplyr::mutate( flag_923bogenCTonly = countFlagfunc( flag_923bogenCTonly))
  flag_923bogenCTonly_plants<-flag_923bogenCTonly_plants %>% dplyr::filter( flag_923bogenCTonly==1)
  flag_923bogenCTonly_plants<-flag_923bogenCTonly_plants %>% dplyr::select(Plant.Code, flag_923bogenCTonly)
  flag_923bogenCTonly_plants<-flag_923bogenCTonly_plants[!duplicated(flag_923bogenCTonly_plants),]
  manualPlants<-merge(manualPlants,flag_923bogenCTonly_plants,by="Plant.Code",all=T)

  flag_NG_no_FH_plants<-data.out %>% dplyr::rowwise() %>% dplyr::mutate( flagNetGenWithoutFuelHeat = countFlagfunc( flagNetGenWithoutFuelHeat))
  flag_NG_no_FH_plants<-flag_NG_no_FH_plants %>% dplyr::filter( flagNetGenWithoutFuelHeat==1)
  flag_NG_no_FH_plants<-flag_NG_no_FH_plants %>% dplyr::select(Plant.Code, flagNetGenWithoutFuelHeat)
  flag_NG_no_FH_plants<-flag_NG_no_FH_plants[!duplicated(flag_NG_no_FH_plants),]
  manualPlants<-merge(manualPlants,flag_NG_no_FH_plants,by="Plant.Code",all=T)
  

  data.out<-data.out %>% dplyr::rowwise() %>% dplyr::mutate(flagFuelHeat = ifelse(regexpr("NGCC",Bogen)>0 | regexpr("ST",Bogen)>0,0,flagFuelHeat))
  flag_fuelheat_plants<-data.out %>% dplyr::rowwise() %>% dplyr::mutate( flagFuelHeat = countFlagfunc( flagFuelHeat))
  flag_fuelheat_plants<-flag_fuelheat_plants %>% dplyr::filter( flagFuelHeat==1)
  flag_fuelheat_plants<-flag_fuelheat_plants %>% dplyr::select(Plant.Code, flagFuelHeat)
  flag_fuelheat_plants<-flag_fuelheat_plants[!duplicated(flag_fuelheat_plants),]
  manualPlants<-merge(manualPlants,flag_fuelheat_plants,by="Plant.Code",all=T)
  
  data.out<-data.out %>% dplyr::rowwise() %>% dplyr::mutate(missingPlant.assoc = ifelse(regexpr("NGCC",Bogen)>0 | regexpr("ST",Bogen)>0,
                                                                                           FALSE,missingPlant.assoc))
  missingPlant.assoc_plants<-data.out %>% dplyr::rowwise() %>% dplyr::mutate(missingPlant.assoc = countFlagfunc(missingPlant.assoc))
  missingPlant.assoc_plants<-missingPlant.assoc_plants %>% dplyr::filter(missingPlant.assoc==1)
  missingPlant.assoc_plants<-missingPlant.assoc_plants %>% dplyr::select(Plant.Code,missingPlant.assoc)
  missingPlant.assoc_plants<-missingPlant.assoc_plants[!duplicated(missingPlant.assoc_plants),]
  manualPlants<-merge(manualPlants,missingPlant.assoc_plants,by="Plant.Code",all=T)

  #flag ST associated with CT,CS,CA
  flag_STassoc_CT_CS_CA_plants<-data.out %>% dplyr::rowwise() %>% dplyr::mutate(flag_STassoc_CT_CS_CA = countFlagfunc(flag_STassoc_CT_CS_CA))
  flag_STassoc_CT_CS_CA_plants<-flag_STassoc_CT_CS_CA_plants %>% dplyr::filter(flag_STassoc_CT_CS_CA==1)
  flag_STassoc_CT_CS_CA_plants<-flag_STassoc_CT_CS_CA_plants %>% dplyr::select(Plant.Code,flag_STassoc_CT_CS_CA)
  flag_STassoc_CT_CS_CA_plants<-flag_STassoc_CT_CS_CA_plants[!duplicated(flag_STassoc_CT_CS_CA_plants),]
  manualPlants<-merge(manualPlants,flag_STassoc_CT_CS_CA_plants,by="Plant.Code",all=T)
  

  #flag CS associated with any other RPM
  flag_CSassociation_plants<-data.out %>% dplyr::rowwise() %>% dplyr::mutate(flag_CSassociation = countFlagfunc(flag_CSassociation))
  flag_CSassociation_plants<-flag_CSassociation_plants %>% dplyr::filter(flag_CSassociation==1)
  flag_CSassociation_plants<-flag_CSassociation_plants %>% dplyr::select(Plant.Code,flag_CSassociation)
  flag_CSassociation_plants<-flag_CSassociation_plants[!duplicated(flag_CSassociation_plants),]
  manualPlants<-merge(manualPlants,flag_CSassociation_plants,by="Plant.Code",all=T)

  flag.NGCC.badFuel_plants<-data.out %>% dplyr::rowwise() %>% dplyr::mutate(flag.NGCC.badFuel = countFlagfunc(flag.NGCC.badFuel))
  flag.NGCC.badFuel_plants<-flag.NGCC.badFuel_plants %>% dplyr::filter(flag.NGCC.badFuel==1)
  flag.NGCC.badFuel_plants<-flag.NGCC.badFuel_plants %>% dplyr::select(Plant.Code,flag.NGCC.badFuel)
  flag.NGCC.badFuel_plants<-flag.NGCC.badFuel_plants[!duplicated(flag.NGCC.badFuel_plants),]
  manualPlants<-merge(manualPlants,flag.NGCC.badFuel_plants,by="Plant.Code",all=T)

  
  #Fill.Gen.ID is an argument passed to the function giving the user the option to fill missing
  #boiler and generator IDs with the association boiler or generator ID when present.
  
  #group months together in data.out
  nonMonths<-data.out
  for (m in months){
    nonMonths<-nonMonths[,names(nonMonths)[regexpr(m,names(nonMonths))<0]]
    if (m=="January"){
      monthData<-data.out[,names(data.out)[regexpr(m,names(data.out))>0]]
    }else{
     monthData<-cbind(monthData,data.out[,names(data.out)[regexpr(m,names(data.out))>0]]) 
    }
  }
data.out<-cbind(nonMonths[1:7],monthData,nonMonths[8:length(nonMonths)])

data.out<-data.out[!duplicated(data.out),]  
data.out$YEAR<-rep(analysisYear,nrow(data.out))

if (analysisYear>2005){
 data.out.list <- list(bogen.key=data.out,NA.BOILER.ID=na.Boiler.ID,bogen=bogen, 
                        checkPlants = checkPlants, Boiler.ID_NotAssoc = Boiler.ID_NotAssoc,
                        compare_RPM=compare_RPM,missingCSCT = missingCSCT,manualPlants=manualPlants,decembrist=decembrist) 
}else{
  data.out.list <- list(bogen.key=data.out,NA.BOILER.ID=na.Boiler.ID,bogen=bogen, 
                        checkPlants = checkPlants, Boiler.ID_NotAssoc = Boiler.ID_NotAssoc,
                        missingCSCT = missingCSCT,
                        manualPlants=manualPlants) 
}
  
  
  return(data.out.list)
}
