#'@title executeBogenAssoc
#'@description Creates a list including a data.frame of boiler-generator (bogen) associations
#'using the `inputData.list$bogen`, `inputData.list$gen_fuel_data`, `inputData.list$boilerFuelData`,
#'`inputData.list$generation.data`,`inputData.list$gen_860`,`inputData.list$retiredGenerators`,
#'`inputData.list$boilerDesignData` and the `bogen_associate()` function.
#'@param inputData.list list object generated by the importThermoEIA::import_EIAData() function 
#'This data is pulled from the EIA website (https://www.eia.gov/electricity/) for the year 
#'of 2015 and has been run through the necessary formatting to be used by the EIAplantAssociation 
#'package.  inputData.list should be in the same format as the example `inputData.list2015` data
#'object.
#'@param plantList data.frame indicating which plants to include in the analysis.  Must contain 
#'the column "Plant.Code".  The `data("masterPlantList")` data object contains a list of recommended
#'plants for analysis for the years 2008-2020.
#'@param select_RPM vector of character strings indicating which Reported.Prime.Mover types should be
#'included in the boiler-generator association output.
#'@param pathWrite character string path to write bogen association output csv files
#'@param eia_year numeric value indicating the year of EIA data present in the `inputData.list`.
#'@param printStatus TRUE/FALSE indicating whether function status messages should print.
#'@return list object with the following contents \cr \cr 
#'\tabular{ll}{
#'`sheet3_key` \tab data.frame containing boiler-generator (bogen) associations by Boiler.ID \cr
#'`sheet4_key` \tab data.frame containing boiler-generator (bogen) associations by Generator.ID \cr
#'`missingCSCT` \tab data.frame of Natural Gas Combined Cycle plants with inconsitent data reporting
#'in the EIA Form-923 across "Page 3 Boiler Fuel Data", "Page 4 Generator Data", and "Page 1 
#'Generation and Fuel Data".  If data is present on "Page 1 Generation and Fuel Data" and not in
#'"Page 3 Boiler Fuel Data" and/or "Page 4 Generator Data", the boiler-generator association will take
#'the form Plant.Code^NGCC and  the `condenserDuty` package will calculate condenser duty using 
#'"Page 1 Generation and Fuel Data" \cr
#'`NA.BOILER.ID` \tab data.frame of all Generators that could not be associated with a non-missing Boiler.ID.
#'Note this does not exclude the plant from the `bogen.key` but condenserDuty will not be calculated at
#'the boiler-generator level it will be calculated at the Plant.Code-Reported.Prime.Mover level.  See 
#'Section ... in the EIAplantAssociation vignette. \cr
#'`Boiler.ID_NotAssoc` \tab data.frame of Boiler.IDs found in `inputData.list$boilerFuelData` that 
#'are not present in the EIA boiler-generator association table `inputData.list$bogen` and cannot be
#'associated by any means other than a string matched flags in the `bogen.key$bga.source` as 
#'"fillwithGenID". \cr
#'`bogen.key` \tab data.frame containing boiler-generator (bogen) associations, flags 
#'detailed in the `data(ColumnLegend_metafile)`.  To view the `data(ColumnLegend_metafile)` object use 
#'the `writeColumnLegend_metafile()` function. \cr
#'`binary_Auto3` \tab data.frame of all flags in `sheet3_key` as binary (0 or 1) \cr
#'`binary_Auto4` \tab data.frame of all flags in `sheet4_key` as binary (0 or 1) \cr
#'`bf.923.ungrouped` data.frame of monthly Fuel Heat by line in `inputData.list$boilerFuelData` \cr
#'`generation.data.line124` data.frame of monthly Net Generation by line in 
#'`inputData.list$generation.data` \cr
#'`bf.gb` data.frame of monthly Fuel Heat by Boiler.ID \cr
#'`generation.data.gb` data.frame of monthly Net Generation by Generator.ID \cr
#'`sumFuelHeatByBogen` data.frame of monthly Fuel Heat by Bogen \cr
#'`sumNetGenByBogen` data.frame of monthly Net Generation by Bogen \cr
#'`thermalEffByBogen` data.frame of monthly Thermal Efficiency by Bogen \cr
#'
#'}
#'@examples
#'#set arguments
#'dest<-tempdir()
#'eia_year<-2015
#'path_InputData_Metafile<-paste0(dest,.Platform$file.sep,"UserControlCrosswalk2015.xlsx")
#'path_EIAInputData<-paste0(dest,.Platform$file.sep,eia_year)
#'outputCSV<-FALSE
#'path_outputCSV<-dest
#'
#'#use crosswalk2015 object
#'useStandardCrosswalk<-TRUE
#'prepCondenserDuty<-TRUE
#'
#'#pull data from web
#'importThermoEIA::eia_webpull(eia_year,dest)
#'
#'
#'#run import using crosswalk2015
#'inputData.list<-importThermoEIA::import_EIAData(path_InputData_Metafile,path_EIAInputData,outputCSV,
#'                               path_outputCSV,prepCondenserDuty = TRUE,eia_year=eia_year,
#'                               useStandardCrosswalk=useStandardCrosswalk)
#'
#'#set year for analysis
#'eia_year<-2015
#'
#'#select Reported.Prime.Movers to include
#'select_RPM<-c("CA", "CS", "CT", "ST",NA)
#'
#'#load MasterPlantList
#'utils::data("masterPlantList")
#'plantList<-masterPlantList[masterPlantList$year==eia_year,]
#'
#'#set output path
#'pathWrite<-tempDir()
#'
#'#run boiler-generator associations
#'bogen.out.list<-executeBogenAssoc(inputData.list,plantList,
#'                            select_RPM,pathWrite,eia_year)
#'
#'@export


executeBogenAssoc<-function(inputData.list,plantList,
                            select_RPM=c("CA", "CS", "CT", "ST",NA),
                            pathWrite,eia_year,printStatus=TRUE){
  
  #unpack input data
  list2env(inputData.list,envir = parent.frame())
  
  generator.data<-gen_860

  
  #nukes
  nukes<-inputData.list$gen_fuel_data %>% dplyr::filter((!is.na(Nuclear.Unit.Id) & Nuclear.Unit.Id!=".") & 
                                                   Plant.Code %in% plantList$Plant.Code)
  nonNukes<-inputData.list$gen_fuel_data %>% dplyr::filter((is.na(Nuclear.Unit.Id) & 
                                                       Reported.Prime.Mover %in% select_RPM &
                                                       Plant.Code %in% plantList$Plant.Code) |
                                                      (Nuclear.Unit.Id=="." & 
                                                         Reported.Prime.Mover %in% select_RPM &
                                                         Plant.Code %in% plantList$Plant.Code))
  
  #complexNukes
  complexNukes<-nonNukes[nonNukes$Plant.Code %in% nukes$Plant.Code,]$Plant.Code
  
  #nukeOnly plants
  nukePlants<-nukes %>% dplyr::filter(!Plant.Code %in% complexNukes)
  
  #Generate boiler and generator associations# 
  bogen.key<-bogen_associate(analysisYear = eia_year,inputData.list,
                             plantList,select_RPM)
  
  #get flags for changed IDS
  bogenFlag<-bogen.key$bogenFlag
  
  #save NAs
  NA.BOILER.ID<-bogen.key$NA.BOILER.ID
  
  #possible problem plants
  checkPlants<-bogen.key$checkPlants
  
  #Boiler.IDs not in association table
  Boiler.ID_NotAssoc = bogen.key$Boiler.ID_NotAssoc
  
  #inconsistent PM
  compare_RPM<-bogen.key$compare_RPM
  
  #manualPLants
  manualPlants<-bogen.key$manualPlants
  
  missingCSCT<-bogen.key$missingCSCT
  
  #get only key
  bogen.key<-bogen.key$bogen.key
  
  #make complex nukes unique
  bogen.key<-bogen.key %>% dplyr::mutate(Bogen = ifelse(Plant.Code %in% 
                                                      complexNukes,paste0(Bogen,".NonNuke"),Bogen))
  
  #test_bogen.key<-bogen.key
  #save(test_bogen.key,file="E:/Corona_VPN/Repos/Thermoelectric_github/2_physical_models/models/associationScripts/test/test_bogen.key")
  
  
  #Select unique boilers and their Bogen code from Bogen key list (sheet3key)
  #take rows with max countFlags
  unique.boilers<-bogen.key %>% 
    dplyr::group_by(Plant.Code,Boiler.ID,Reported.Prime.Mover_page1) %>%
    dplyr::slice(which.min(missing.bf.923))
  
  
  assign("unique.boilers",unique.boilers,envir = .GlobalEnv)
  
  
  #Select unique generating units (sheet4key)
  #take rows with max countFlags
  unique.generators<-bogen.key %>% 
    dplyr::group_by(Plant.Code,Generator.ID,Reported.Prime.Mover_page1) %>%
    dplyr::slice(which.max(countFlags))
  
  #remove nuclear plants
  #nukePlants$Plant.Code<-sapply(nukePlants$combogencoo, function(x) as.numeric(strsplit(as.character(x),"\\^")[[1]][2]))
  unique.boilers<-unique.boilers[!unique.boilers$Plant.Code %in% nukePlants$Plant.Code,]
  unique.generators<-unique.generators[!unique.generators$Plant.Code %in% nukePlants$Plant.Code,]
  
  
  sheet3_key<-unique.boilers
  
  #create plant_bo column
  sheet3_key$plant_bo<-paste0(sheet3_key$Plant.Code,"^",ifelse(!is.na(sheet3_key$Boiler.ID),sheet3_key$Boiler.ID,"NA"))
  sheet3_key$plant_bo_bf.923<-paste0(sheet3_key$Plant.Code,"^",ifelse(!is.na(sheet3_key$orig_Boiler.ID_bf.923),sheet3_key$orig_Boiler.ID_bf.923,"NA"))
  sheet3_key$plant_bo_assoc<-paste0(sheet3_key$Plant.Code,"^",ifelse(!is.na(sheet3_key$orig_Boiler.ID_assoc),sheet3_key$orig_Boiler.ID_assoc,"NA"))
  
  sheet4_key<-unique.generators
  
  #create plant_gen column
  sheet4_key$plant_gen<-paste0(sheet4_key$Plant.Code,"^",ifelse(!is.na(sheet4_key$Generator.ID),sheet4_key$Generator.ID,"NA"))
  sheet4_key$plant_gen.923<-paste0(sheet4_key$Plant.Code,"^",ifelse(!is.na(sheet4_key$orig_Generator.ID_923),sheet4_key$orig_Generator.ID_923,"NA"))
  sheet4_key$plant_gen.860<-paste0(sheet4_key$Plant.Code,"^",ifelse(!is.na(sheet4_key$orig_Generator.ID_860),sheet4_key$orig_Generator.ID_860,"NA"))
  sheet4_key$plant_gen_assoc<-paste0(sheet4_key$Plant.Code,"^",ifelse(!is.na(sheet4_key$orig_Generator.ID_assoc),sheet4_key$orig_Generator.ID_assoc,"NA"))
  assign("sheet3_key84",sheet3_key,envir = .GlobalEnv)
  #format columns
  names(sheet3_key)[names(sheet3_key)=="Bogen"]<-"bogen"
  names(sheet4_key)[names(sheet4_key)=="Bogen"]<-"bogen"
  
  #remove duplicates
  sheet3_key<-sheet3_key[!duplicated(sheet3_key),]
  sheet3_key<-sheet3_key[!is.na(sheet3_key$plant_bo),]
  sheet4_key<-sheet4_key[!duplicated(sheet4_key),]
  sheet4_key<-sheet4_key[!is.na(sheet4_key$plant_gen),]
  assign("sheet3_key94",sheet3_key,envir = .GlobalEnv)
  #remove Boilers with No boilerFuelData and Generators with No generation.data
  sheet3_key<-sheet3_key[sheet3_key$flag_Boiler.Status!=1 | regexpr("NGCC",sheet3_key$bogen)>0 | regexpr("ST",sheet3_key$bogen)>0,]
  sheet3_key<-sheet3_key %>% dplyr::filter(missing.bf.923!=TRUE | regexpr("NGCC",bogen)>0 | regexpr("ST",bogen)>0)
  assign("sheet3_key98",sheet3_key,envir = .GlobalEnv)
  noGenData<-generation.data
  noGenData$Generator.ID <- as.character(noGenData$Generator.ID)
  noGenData<-noGenData %>% dplyr::filter(Plant.Code %in% plantList$Plant.Code)
  noGenData$flagGenerator.ID_923<-sapply(noGenData$Generator.ID, function(x) ifelse(grepl("(?<![0-9])",x,perl=TRUE),"removeChar",
                                                                                                ifelse(grepl(" ",x,perl=TRUE),"removeSpace",NA)))
  noGenData$orig_Generator.ID_923<-noGenData$Generator.ID
  noGenData$Generator.ID <- gsub("(?<![0-9])", "", noGenData$Generator.ID , perl = TRUE)
  noGenData$Generator.ID <- gsub("[[:space:]]", "", noGenData$Generator.ID )
  noGenData<-removeLeadZero(noGenData,"Generator.ID","flagGenerator.ID_923")
  noGenData<-dplyr::anti_join(sheet4_key[,names(sheet4_key)!="Reported.Prime.Mover_page1"],noGenData,by=c("Plant.Code","Generator.ID"))
  noGenData$missing.generation.data<-rep(TRUE,nrow(noGenData))
  noGenData<-noGenData %>% dplyr::select(Plant.Code,Generator.ID,missing.generation.data)
  sheet4_key<-merge(sheet4_key,noGenData,by=c("Plant.Code","Generator.ID"), all.x = TRUE)
  assign("sheet4_key112",sheet4_key,envir = .GlobalEnv)
  sheet4_key$missing.generation.data<-ifelse(is.na(sheet4_key$missing.generation.data) | regexpr("NGCC",sheet4_key$bogen)>0 | regexpr("ST",sheet4_key$bogen)>0,FALSE,TRUE)
  sheet4_key<-sheet4_key %>% dplyr::filter(!missing.generation.data)
  sheet4_key<-sheet4_key[!duplicated(sheet4_key),]
  assign("sheet4_key115",sheet4_key,envir = .GlobalEnv)
  #format FH and NG tables for compiled file
  sheet3_key<-dplyr::ungroup(sheet3_key)
  bf.923.ungrouped<-merge(bf.923.ungrouped,sheet3_key %>% dplyr::select(Plant.Code,Boiler.ID,bogen,-Reported.Prime.Mover_page1),
                          by=c("Plant.Code","Boiler.ID"))
  bf.923.ungrouped<-bf.923.ungrouped[!duplicated(bf.923.ungrouped),]
  if (eia_year>2005){
   bf.923.ungrouped<-bf.923.ungrouped %>% dplyr::select(Plant.Code,Boiler.ID,bogen,Reported.Prime.Mover_bf.923,
                                                Reported.Fuel.Type.Code,dplyr::contains("Fuel.Heat"),YEAR) 
  }else{
    bf.923.ungrouped<-bf.923.ungrouped %>% dplyr::select(Plant.Code,Boiler.ID,bogen,
                                                  Reported.Fuel.Type.Code,dplyr::contains("Fuel.Heat"),YEAR) 
  }
  
  sheet4_key<-dplyr::ungroup(sheet4_key)
  generation.data.line124<-merge(generation.data.line124,sheet4_key %>% dplyr::select(Plant.Code,Generator.ID,bogen,-Reported.Prime.Mover_page1),
                          by=c("Plant.Code","Generator.ID"))
  generation.data.line124<-generation.data.line124[!duplicated(generation.data.line124),]
  if (eia_year>2005){
    generation.data.line124<-generation.data.line124 %>% dplyr::select(Plant.Code,Generator.ID,bogen,Reported.Prime.Mover,
                                                              Net.Generation.Year.To.Date,dplyr::contains("Net.Generation"),YEAR)
  }else{
    generation.data.line124<-generation.data.line124 %>% dplyr::select(Plant.Code,Generator.ID,bogen,
                                                                Net.Generation.Year.To.Date,dplyr::contains("Net.Generation"),YEAR)
  }
  
  if (eia_year>2005){
     bfd.gb<-merge(bfd.gb,sheet3_key %>% dplyr::select(Plant.Code,Boiler.ID,bogen,Reported.Prime.Mover_bf.923,flagFuelHeat),
                by=c("Plant.Code","Boiler.ID")) 
  }else{
    bfd.gb<-merge(bfd.gb,sheet3_key %>% dplyr::select(Plant.Code,Boiler.ID,bogen,flagFuelHeat),
                  by=c("Plant.Code","Boiler.ID")) 
  }

  noDupsYear<-bf.923.ungrouped %>% dplyr::select(Plant.Code,Boiler.ID,YEAR)
  noDupsYear<-noDupsYear[!duplicated(noDupsYear),]
  bfd.gb<-merge(bfd.gb,noDupsYear,by=c("Plant.Code","Boiler.ID"))
  if (eia_year>2005){
   bfd.gb<-bfd.gb %>% dplyr::select(Plant.Code,Boiler.ID,bogen,Reported.Prime.Mover_bf.923,flagFuelHeat,dplyr::contains("Fuel.Heat"),YEAR)  
  }else{
    bfd.gb<-bfd.gb %>% dplyr::select(Plant.Code,Boiler.ID,bogen,flagFuelHeat,dplyr::contains("Fuel.Heat"),YEAR)  
  }
  
  noDupsYear<-generation.data.line124 %>% dplyr::select(Plant.Code,Generator.ID,YEAR)
  noDupsYear<-noDupsYear[!duplicated(noDupsYear),]
  generation.data.gb<-merge(generation.data.gb,noDupsYear,by=c("Plant.Code","Generator.ID"))
  if (eia_year>2005){
    generation.data.gb<-merge(generation.data.gb,sheet4_key %>% dplyr::select(Plant.Code,Generator.ID,bogen,
                                                                       Reported.Prime.Mover_923),
                              by=c("Plant.Code","Generator.ID"))
    generation.data.gb<-generation.data.gb %>% dplyr::select(Plant.Code,Generator.ID,bogen,Reported.Prime.Mover_923,
                                                      Net.Generation.mwh,dplyr::contains("Net.Generation"),YEAR)
    noDupsforFH<-bfd.gb %>% dplyr::select(Plant.Code,bogen,Reported.Prime.Mover_bf.923,flagFuelHeat,YEAR)
  }else{
  generation.data.gb<-merge(generation.data.gb,sheet4_key %>% dplyr::select(Plant.Code,Generator.ID,bogen),
                            by=c("Plant.Code","Generator.ID"))
  
  generation.data.gb<-generation.data.gb %>% dplyr::select(Plant.Code,Generator.ID,bogen,
                                                    Net.Generation.mwh,dplyr::contains("Net.Generation"),YEAR)
  
  noDupsforFH<-bfd.gb %>% dplyr::select(Plant.Code,bogen,flagFuelHeat,YEAR)
  }
  
  noDupsforFH<-noDupsforFH[!duplicated(noDupsforFH),]
  names(sumFuelHeatByBogen)[which(names(sumFuelHeatByBogen)=="Bogen")]<-"bogen"
  sumFuelHeatByBogen<-merge(sumFuelHeatByBogen,noDupsforFH,by=c("Plant.Code","bogen"),all.x = TRUE)
  sumFuelHeatByBogen$blankCol<-rep("",nrow(sumFuelHeatByBogen))
  sumFuelHeatByBogen$YEAR<-rep(eia_year,nrow(sumFuelHeatByBogen))
  if(eia_year>2005){
    sumFuelHeatByBogen<-sumFuelHeatByBogen %>% dplyr::select(Plant.Code,blankCol,bogen,Reported.Prime.Mover_bf.923,flagFuelHeat,
                                                      dplyr::contains("Fuel.Heat"),YEAR) 
    noDupsforNG<-generation.data.gb %>% dplyr::select(Plant.Code,bogen,Reported.Prime.Mover_923,Net.Generation.mwh,YEAR)

  }else{
  sumFuelHeatByBogen<-sumFuelHeatByBogen %>% dplyr::select(Plant.Code,blankCol,bogen,flagFuelHeat,
                                                    dplyr::contains("Fuel.Heat"),YEAR)

  noDupsforNG<-generation.data.gb %>% dplyr::select(Plant.Code,bogen,Net.Generation.mwh,YEAR)

  }
  noDupsforNG2<-sheet4_key %>% dplyr::select(Plant.Code,bogen,Net.Generation.mwh)
  noDupsforNG2<-noDupsforNG2 %>% dplyr::group_by(Plant.Code,bogen) %>% dplyr::summarize(Net.Generation.mwh = sum(Net.Generation.mwh,na.rm=TRUE))
  noDupsforNG2<-noDupsforNG2[!duplicated(noDupsforNG2),]
  noDupsforNG<-noDupsforNG[!duplicated(noDupsforNG),]
  names(sumNetGenByBogen)[which(names(sumNetGenByBogen)=="Bogen")]<-"bogen"
  sumNetGenByBogen<-merge(sumNetGenByBogen,noDupsforNG,by=c("Plant.Code","bogen"),all.x=TRUE)
  sumNetGenByBogen[regexpr("NGCC",sumNetGenByBogen$bogen)>0 | regexpr("ST",sumNetGenByBogen$bogen)>0,names(sumNetGenByBogen)!="YEAR"]<-merge(sumNetGenByBogen[regexpr("NGCC",sumNetGenByBogen$bogen)>0 | regexpr("ST",sumNetGenByBogen$bogen)>0,
                   !names(sumNetGenByBogen) %in% c("Net.Generation.mwh","YEAR")],noDupsforNG2 %>% dplyr::filter(regexpr("NGCC",bogen)>0 | regexpr("ST",bogen)>0),
                   by=c("Plant.Code","bogen"), all.x=TRUE)
  sumNetGenByBogen$YEAR<-rep(eia_year,nrow(sumNetGenByBogen))
  sumNetGenByBogen$blankCol<-rep("",nrow(sumNetGenByBogen))
  if (eia_year>2005){
    sumNetGenByBogen<-sumNetGenByBogen %>% dplyr::select(Plant.Code,blankCol,bogen,Reported.Prime.Mover_923,Net.Generation.mwh,
                                                  dplyr::contains("Net.Generation"),YEAR) 
  }else{
  sumNetGenByBogen<-sumNetGenByBogen %>% dplyr::select(Plant.Code,blankCol,bogen,Net.Generation.mwh,
                                                dplyr::contains("Net.Generation"),YEAR)
  }
  names(thermalEffByBogen)[which(names(thermalEffByBogen)=="Bogen")]<-"bogen"
  thermalEffByBogen<-merge(thermalEffByBogen,noDupsforNG,by=c("Plant.Code","bogen"), all.x=TRUE)
  thermalEffByBogen[regexpr("NGCC",thermalEffByBogen$bogen)>0 | regexpr("ST",thermalEffByBogen$bogen)>0,names(thermalEffByBogen)!="YEAR"]<-merge(thermalEffByBogen[regexpr("NGCC",thermalEffByBogen$bogen)>0 | regexpr("ST",thermalEffByBogen$bogen)>0,
                                                                                                                     !names(thermalEffByBogen) %in% c("Net.Generation.mwh","YEAR")],
                                                                                                       noDupsforNG2 %>% dplyr::filter(regexpr("NGCC",bogen)>0 | regexpr("ST",bogen)>0),
                                                                                                    by=c("Plant.Code","bogen"), all.x=TRUE)
  thermalEffByBogen$YEAR<-rep(eia_year,nrow(thermalEffByBogen))
  thermalEffByBogen$blankCol<-rep("",nrow(thermalEffByBogen))
  if (eia_year>2005){
    thermalEffByBogen<-thermalEffByBogen %>% dplyr::select(Plant.Code,blankCol,bogen,Reported.Prime.Mover_923,Net.Generation.mwh,
                                                    dplyr::contains("ThermalEfficiency"),YEAR)
  }else{
  thermalEffByBogen<-thermalEffByBogen %>% dplyr::select(Plant.Code,blankCol,bogen,Net.Generation.mwh,
                                                dplyr::contains("ThermalEfficiency"),YEAR)
  }
  sheet3_key<-sheet3_key %>% dplyr::select(-Generator.ID,-dplyr::contains("Net.Generation"),-dplyr::contains("Generator"),-dplyr::contains("NetGen"))
  sheet4_key<-sheet4_key %>% dplyr::select(-Boiler.ID,-dplyr::contains("Boiler"))
  
  sheet3_key$manualEdit<-integer(nrow(sheet3_key))
  sheet3_key<-sheet3_key %>% dplyr::select(manualEdit,names(sheet3_key))
  sheet4_key$manualEdit<-integer(nrow(sheet4_key))
  sheet4_key<-sheet4_key %>% dplyr::select(manualEdit,names(sheet4_key))
  
  #Binary flags for compiled file
  data("ColumnLegend_metafile")
  flagList<-ColumnLegend_metafile
  flagList<-flagList[1:30,1]
  if (eia_year<=2005){
    flagList<-flagList[!flagList %in% c("flag_RPM","flag_923bogenCTonly")]
  }
  
  months<-c("January","February","March","April","May",
            "June","July","August","September","October","November","December")
  for (m in months){
    
    strflagList<-paste0("subflaglist<-c('flagFH_no_NG_",m,"','flagNG_no_FH_",m,"','flagFuelHeat_",m,"')")
    eval(parse(text=strflagList))
    flagList<-c(flagList,subflaglist)
    
  }
  
  #add countFlags column
  countFlagfunc<-function(f){
    if (!is.na(f)){
      if(f==TRUE){
        c<-1
      }else if(!class(f) %in% c("factor","character","logical")){
        if(f!=0){
          c<-1
        }else if(f==0){
          c<-0
        }
      }else if (f %in% c("OS","OA","RE")){
        c<-1
      }else if(f==FALSE){
        c<-0
      }else{#no flag
        c<-0
      }
    }else{#missing flag
      c<-0
    }
    return(c)
  }
  
  for (f in flagList){
    if (regexpr("generator",tolower(f))<0 & regexpr("net.generation",tolower(f))<0 & 
        regexpr("netgen",tolower(f))<0 & regexpr("missing.generation.data",tolower(f))<0){
      if (f==flagList[1]){
        
        eval(parse(text=paste0("binary_onlyAuto<-sheet3_key %>% dplyr::rowwise() %>% dplyr::mutate(",f," = sum(countFlagfunc(",f,")))")))
        
      }else{
        if (tolower(f) %in% tolower(names(sheet3_key))){
        eval(parse(text=paste0("binary_onlyAuto<-binary_onlyAuto %>% dplyr::rowwise() %>% dplyr::mutate(",f," = sum(countFlagfunc(",f,")))")))
        }
      }
    }
  }
  
  binary_Auto3<-binary_onlyAuto %>% dplyr::select(Plant.Code,plant_bo,bogen,flagList[which(flagList %in% names(binary_onlyAuto))])

  
  for (f in flagList){
    if (regexpr("boiler",tolower(f))<0){
      if (f==flagList[1]){
        
        eval(parse(text=paste0("binary_onlyAuto<-sheet4_key %>% dplyr::rowwise() %>% dplyr::mutate(",f," = sum(countFlagfunc(",f,")))")))
      }else{
        eval(parse(text=paste0("binary_onlyAuto<-binary_onlyAuto %>% dplyr::rowwise() %>% dplyr::mutate(",f," = sum(countFlagfunc(",f,")))")))
      }
    }
  }
  
  binary_Auto4<-binary_onlyAuto %>% dplyr::select(Plant.Code,plant_gen,bogen,flagList[which(flagList %in% names(binary_onlyAuto))])
  
  
  #outputKeys
  utils::write.csv(sheet3_key,file=paste0(pathWrite,"auto_sheet3_bogen.key.csv"),row.names = F)
  utils::write.csv(sheet4_key,file=paste0(pathWrite,"auto_sheet4_bogen.key.csv"),row.names = F)
  
  #output flags
  utils::write.csv(manualPlants,paste0(pathWrite,"manualPlants.csv"),row.names = F)
  utils::write.csv(NA.BOILER.ID,paste0(pathWrite,"NA.BOILER.ID.csv"),row.names = F)
  utils::write.csv(data.frame(Plant.Code = checkPlants),paste0(pathWrite,"FloatingGenerators.csv"),row.names = F)
  utils::write.csv(Boiler.ID_NotAssoc,paste0(pathWrite,"OrphanBoilers.csv"),row.names = F)
  utils::write.csv(compare_RPM,paste0(pathWrite,"Inconsistent_RPM.csv"),row.names = F)
  
  

  bogen.out.list<-named.list(sheet3_key,sheet4_key,missingCSCT,manualPlants,NA.BOILER.ID,Boiler.ID_NotAssoc, 
                             bogen.key,binary_Auto3,binary_Auto4,bf.923.ungrouped,generation.data.line124,
                             bfd.gb,generation.data.gb,sumFuelHeatByBogen,sumNetGenByBogen,thermalEffByBogen)
  return(bogen.out.list)
}