#'@title fileMissingPlants
#'@description Finds Plant.Codes that are in the `plantList` but missing from one of the 
#'following tables \cr \cr
#'\itemize{  \item `inputData.list$bogen`
#'           \item `inputData.list$gen_860`
#'           \item `inputData.list$generation.data`
#'           \item `inputData.list$boilerFuelData`
#'           \item `inputData.list$boilerDesignData`
#'           \item `inputData.list$retiredGenerators`
#'           } \cr \cr
#'@param plantList numeric vector of Plant.Codes to consider
#'@param inputData.list list object generated by the importThermoEIA::import_EIAData() function 
#'This data is pulled from the EIA website (https://www.eia.gov/electricity/) for the year 
#'of 2015 and has been run through the necessary formatting to be used by the EIAplantAssociation 
#'package.  inputData.list should be in the same format as the example `inputData.list2015` data
#'object.
#'@return data.frame with the following columns \cr \cr
#'\itemize{\item    "Plant.Code"
#'           \item  "missingPlant.assoc" TRUE/FALSE indicating Plant.Code missing from `inputData.list$bogen`
#'           \item  "missingPlant.generator.data.860" TRUE/FALSE indicating Plant.Code missing from `inputData.list$gen_860` and `inputData.list$retiredGenerators`
#'           \item  "missingPlant.generation.data.923" TRUE/FALSE indicating Plant.Code missing from `inputData.list$generation.data`
#'           \item  "missingPlant.boilerFuelData.923" TRUE/FALSE indicating Plant.Code missing from `inputData.list$boilerFuelData`
#'           \item  "missingPlant.boilerDesignData.860" TRUE/FALSE indicating Plant.Code missing from `inputData.list$boilerDesignData`
#'           } \cr \cr
#'@examples
#'#set arguments
#'dest<-tempdir()
#'eia_year<-2015
#'path_InputData_Metafile<-paste0(dest,.Platform$file.sep,"UserControlCrosswalk2015.xlsx")
#'path_EIAInputData<-paste0(dest,.Platform$file.sep,eia_year)
#'outputCSV<-FALSE
#'path_outputCSV<-dest
#'
#'#use crosswalk2015 object
#'useStandardCrosswalk<-TRUE
#'prepCondenserDuty<-TRUE
#'
#'#pull data from web
#'importThermoEIA::eia_webpull(eia_year,dest)
#'
#'
#'#run import using crosswalk2015
#'inputData.list<-importThermoEIA::import_EIAData(path_InputData_Metafile,path_EIAInputData,outputCSV,
#'                               path_outputCSV,prepCondenserDuty = TRUE,eia_year=eia_year,
#'                               useStandardCrosswalk=useStandardCrosswalk)
#'
#'#get masterPlantList
#'data("masterPlantList")
#'plantList<-masterPlantList[masterPlantList$year==2015,]$Plant.Code
#'
#'fileMissingPlants(plantList,inputData.list)
#'@export

fileMissingPlants<-function(plantList,inputData.list){
  
  #unpack input data
  list2env(inputData.list,envir = parent.frame())
  
  generator.data<-gen_860
  
  #flag Plant not in input table
  missingPlants<-data.frame(Plant.Code=unique(plantList),
                            missingPlant.assoc = rep(FALSE,length(unique(plantList))),
                            missingPlant.generator.data.860 = rep(FALSE,length(unique(plantList))),
                            missingPlant.boilerDesignData.860 = rep(FALSE,length(unique(plantList))),
                            missingPlant.generation.data.923 = rep(FALSE,length(unique(plantList))),
                            missingPlant.boilerFuelData.923 = rep(FALSE,length(unique(plantList))))
  for (p in plantList){
    subData<-bogen %>% dplyr::filter(Plant.Code==p)
    if (nrow(subData)==0){
      missingPlants[missingPlants$Plant.Code==p,]$missingPlant.assoc<-TRUE
    }
    
    subData<-generator.data %>% dplyr::filter(Plant.Code==p)
    subData2<-retiredGenerators %>% dplyr::filter(Plant.Code==p)
    if (nrow(subData)==0 & nrow(subData2)==0){
      missingPlants[missingPlants$Plant.Code==p,]$missingPlant.generator.data.860<-TRUE
    }
    
    subData<-boilerDesignData %>% dplyr::filter(Plant.Code==p)
    if (nrow(subData)==0){
      missingPlants[missingPlants$Plant.Code==p,]$missingPlant.boilerDesignData.860<-TRUE
    }
    
    subData<-generation.data %>% dplyr::filter(Plant.Code==p)
    if (nrow(subData)==0){
      missingPlants[missingPlants$Plant.Code==p,]$missingPlant.generation.data.923<-TRUE
    }
    
    subData<-boilerFuelData %>% dplyr::filter(Plant.Code==p)
    if (nrow(subData)==0){
      missingPlants[missingPlants$Plant.Code==p,]$missingPlant.boilerFuelData.923<-TRUE
    }
  }
  
  return(missingPlants)
}